### ISSUE TITLE
Error reading character data for character in 1.9.2

### ISSUE THREAD

**Issue by Gusmonkey** [Stickymaddness/Procurement#100]
The log info:
```
[29-04-2015 16:03] System.Exception: Error reading character data for Sappharina, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by Stickymaddness** [comment]
Make sure that you have the account name field filled in, note that it is case sensitive!

**Comment by Stickymaddness** [comment]
Closing due to inactivity, please open a new ticket if this is still an issue.

To clarify the account name field:

![accountname](https://cloud.githubusercontent.com/assets/6553902/7933116/4fd693e8-091d-11e5-80f5-eda0bde0a530.PNG)
