### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by animesenpaida** [Stickymaddness/Procurement#1001]
[19-03-2019 12:46] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[19-03-2019 12:46] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by aydjay** [comment]
Make sure you login to the path of exile website and grab the fresh POE Session ID.

**Comment by animesenpaida** [comment]
yup done it thank you :D
