### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by obrac75** [Stickymaddness/Procurement#1011]

**Comment by obrac75** [comment]
Error downloading account name...any help please?tryed to reinstal but still this hapeneing

**Comment by obrac75** [comment]
[01-04-2019 0:26] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[01-04-2019 0:26] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[01-04-2019 0:26] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[01-04-2019 0:26] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by aydjay** [comment]
Make sure you login to the POE Website and generate a new POESSID.
