### ISSUE TITLE
Procurement cant log in at all 

### ISSUE THREAD

**Issue by Ditkobanditko** [Stickymaddness/Procurement#1015]
Hey there been using this program for over 4 years never had issues but now whatever i do wont let me log in here is debug info . 

[14-04-2019 18:27] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
Saw couple of same bugs issue on the site and did what you guys recommended still dotn work 
Changed path of exile id couple of times deleted procurement reinstalled it result is the same always no matter how many id i change i get the above bug info . Added procurement to antivirus program to win firewall still wont work please any help is apritiated ty in advance

**Comment by thailyn** [comment]
Hi, can you provide the full contents of your `DebugInfo.log` file?  By "path of exile id" you mean the POE Session ID?  And you changed it by logging out and back in on the pathofexile.com website?  You're using the [latest version](https://github.com/Stickymaddness/Procurement/releases/tag/1.26.1) of Procurement?

**Comment by Ditkobanditko** [comment]
Hi ty for the fast response ^^
So i saw on site that couple of other people had same issue like me i saw
people response was to change path of exile id so i went on the path of
exile site change my e-mail and my password couple of times i belive my
password is my session id if not care to explain what is it ??
. Yes i am using latest Procurement version Procurement 1.26.1
<https://github.com/Stickymaddness/Procurement/releases/tag/1.26.1> .
[15-04-2019 7:20] Failed to build HTTP request and get response for:
method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=,
requestData='': The remote server returned an error: (503) Server
Unavailable.
[15-04-2019 7:20] Failed to build HTTP request and get response for:
method=GET, url='
https://www.pathofexile.com/character-window/get-account-name',
allowAutoRedirects=, requestData='': The remote server returned an error:
(401) Unauthorized.
[15-04-2019 7:20] Error downloading account name, exception details:
System.Net.WebException: The remote server returned an error: (401)
Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at
POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod
method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method,
String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[15-04-2019 7:20] System.Exception: Error downloading account name, details
logged to DebugInfo.log. Please open a ticket at
https://github.com/Stickymaddness/Procurement/issues and include your
DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at
Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[15-04-2019 7:23] Failed to build HTTP request and get response for:
method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=,
requestData='': The remote server returned an error: (503) Server
Unavailable.
[15-04-2019 7:24] Failed to build HTTP request and get response for:
method=GET, url='
https://www.pathofexile.com/character-window/get-account-name',
allowAutoRedirects=, requestData='': The remote server returned an error:
(401) Unauthorized.
[15-04-2019 7:24] Error downloading account name, exception details:
System.Net.WebException: The remote server returned an error: (401)
Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at
POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod
method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method,
String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[15-04-2019 7:24] System.Exception: Error downloading account name, details
logged to DebugInfo.log. Please open a ticket at
https://github.com/Stickymaddness/Procurement/issues and include your
DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at
Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[15-04-2019 7:24] Failed to build HTTP request and get response for:
method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=,
requestData='': The remote server returned an error: (503) Server
Unavailable.
[15-04-2019 7:24] Failed to build HTTP request and get response for:
method=GET, url='
https://www.pathofexile.com/character-window/get-account-name',
allowAutoRedirects=, requestData='': The remote server returned an error:
(401) Unauthorized.
[15-04-2019 7:24] Error downloading account name, exception details:
System.Net.WebException: The remote server returned an error: (401)
Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at
POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod
method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method,
String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[15-04-2019 7:24] System.Exception: Error downloading account name, details
logged to DebugInfo.log. Please open a ticket at
https://github.com/Stickymaddness/Procurement/issues and include your
DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at
Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

Those are my last couple of times trying to log in onto Procurement

**Comment by thailyn** [comment]
The Session ID is different from your password.  For the last two leagues or so GGG has changed how the login process works, and since then Procurement has not supported using your password.  See [this page](https://github.com/Stickymaddness/Procurement/wiki/SessionID) for how to get your Session ID.  The instructions might be slightly out of date; if you have trouble, please let me know which browser you are using to log in to `pathofexile.com`.

**Comment by Ditkobanditko** [comment]
Ty so much for the help it worked first time i try didnt play last 2 leagues so the info you mentioned above sleep from me Thank you  once again fro the fast response and help  ^^

**Comment by aydjay** [comment]
Please close the issue if you are able to login :)
