### ISSUE TITLE
Excluding tabs gives an unhandled error

### ISSUE THREAD

**Issue by Astroelmeria** [Stickymaddness/Procurement#1031]
Every time I choose to exclude a stash from Recipe results, I get a pop-up saying "there was an unhandled error" and Procurement crashes.

**Comment by thailyn** [comment]
I can't recreate this issue.  What version of Procurement are you using?  Also please attach your `DebugInfo.log` file.

**Comment by nqrcqn** [comment]
I get the same crash, DebugInfo shows the same "Failed to get image" errors after the crash as well as this:

> System.ArgumentException: Value does not fall within the expected range. ---> System.ArgumentException: Value does not fall within the expected range
   at System.Windows.Media.Imaging.CroppedBitmap.FinalizeCreation()
   at Procurement.Utility.StashHelper.buildImage(Tab tab, Int32 offset, String key)
   at Procurement.Utility.StashHelper.GenerateTabImage(Tab tab, Boolean mouseOver)
   at Procurement.View.TabIDToStashControlFiltered.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Astroelmeria** [comment]
This happened after I updated from 1.26.1 to 1.27.1. I also tried reinstalling 1.26.1 and got the same error. However, I ended up restoring my old 1.26.1 installation from the Recycle Bin and that one works perfectly fine.

1.26.1 DebugInfo [DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3287244/DebugInfo.log)

1.27.1 DebugInfo [DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3287239/DebugInfo.log)

**Comment by nqrcqn** [comment]
Hi, try this latest build which should fix the crashes along with a tab refresh fix: https://ci.appveyor.com/api/buildjobs/nl2fsxyo6pi2pk5j/artifacts/Procurement%2Fbin%2FProcurement.zip

And copy these 3 files inside your Common folder: https://github.com/Stickymaddness/Procurement/files/3287110/stashtab.zip

**Comment by Astroelmeria** [comment]
Finally got a chance to get the newest release and that did fix all my issues!
