### ISSUE TITLE
1.27.1 [Error] Downloading stash for SSF Standard, 

### ISSUE THREAD

**Issue by kapoda** [Stickymaddness/Procurement#1038]
[17-06-2019 22:52] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[17-06-2019 22:52] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-stash-items?league=SSF Standard&tabs=1&tabIndex=9&accountName=kapoda0&realm=pc', allowAutoRedirects=, requestData='': The remote server returned an error: (429) Too Many Requests.
[17-06-2019 22:52] Error downloading stash for SSF Standard, exception details: System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, String realm)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh, String realm)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, String realm)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, String realm, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetAllTabs(String league, String accountName, Stash stash, String realm)
   at POEApi.Model.POEModel.GetStash(String league, String accountName, String realm)
[17-06-2019 22:52] System.Exception: Downloading stash for SSF Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName, String realm)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3298807/DebugInfo.log)

**Comment by thailyn** [comment]
Is this error happening when you are logging in, or when you are refreshing tabs?

You're getting `(429) Too Many Requests` errors, which means you're sending too many requests to the GGG API.   If you're logged in to Procurement and just refreshing tabs, this should never happen.  It might if you are repeatedly opening and reopening Procurement.  It also can happen if you are using other programs which use your account to access the API.  Do any of these cases describe your situation?

**Comment by kapoda** [comment]
Yes I have exilence in the background too which needs access to the API I will close it and try again

**Comment by thailyn** [comment]
Ok, thanks for the clarification (I also use Exilence alongside Procurement).  I have a pending PR (#985) that will make Procurement more gracefully handle this situation -- wait a while and then retry failed requests, instead of skipping them and continuing to immediately send more requests that will probably fail.  I have another improvement planned after that to improve the behavior more.
