### ISSUE TITLE
cannot load stash, 1.9.2

### ISSUE THREAD

**Issue by trustinvision** [Stickymaddness/Procurement#104]
hello,

I just recently started playing poe and wanted to setup the trade shop. when i run the procurement and enter my details i get this message as it tries to load the first stash tab.

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

full message is 

Authenticating mewha2507@gmail.com                                                        [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

any idea what i can do to fix this?

Regards
Vision

**Comment by IxtreeMas** [comment]
Same here. How to fix this?

**Comment by Stickymaddness** [comment]
Please paste your debuginfo.log so that I can see what the error is.

**Comment by trustinvision** [comment]
Hi thanks for your reply, here is the most recent part of the log file:

[22-05-2015 0:26] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
[22-05-2015 0:26] JSON Serialization Failed: base64 bytes:
[22-05-2015 0:26] ZmFsc2U=
[22-05-2015 0:26] END
[22-05-2015 0:26] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[22-05-2015 0:26] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

Please let me know if I can provide any more info.

Thanks Again

**Comment by Stickymaddness** [comment]
It looks like GGG is returning null (empty) data for your characters/leagues, this is a common issue if you're using steam and your forum account hasn't been properly associated with steam. If you contact GGG support they will be able to fix it for you.
