### ISSUE TITLE
Unhandled exception on 

### ISSUE THREAD

**Issue by Enlightnd** [Stickymaddness/Procurement#1048]
Unhandled error even attempting to open Recipe pane.
Unhandled error selecting anything in "Exclude tab from Recipe results"

Error log:

[06-07-2019 22:54] System.ArgumentException: Value does not fall within the expected range. ---> System.ArgumentException: Value does not fall within the expected range.
   --- End of inner exception stack trace ---
   at Procurement.Utility.StashHelper.buildImage(Tab tab, List`1 images, Bitmap finalImage, Int32 offset, String key)
   at Procurement.Utility.StashHelper.GenerateTabImage(Tab tab, Boolean mouseOver)
   at Procurement.View.TabIDToStashControlFiltered.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

After the application crashes and I go back into the settings, my selection for tabs to exclude from recipe results has been registered.

Currently the only tabs that are included in the recipe search results are my 4 standard tabs and my 2 premium tabs.

Special tabs I have:

Cash
Maps
Essences
Fragments
Uniques
Cards

Once everything except my 4 standard and 2 premium tabs is excluded, Recipe's pane works.

Once I try to unselect my main characters personal inventory in the recipe exclusion settings (I tried flagging on/off all special and all other character inventory tabs) the app crashes again with an unhandled exception.

**Comment by Enlightnd** [comment]
Found another Unhandled exception in the Recipes pane.

When I try to select an item in my Uniques (special) tab, it crashes too.

I found that if I try to open the Uniques tab in the applications inventory screen, the tab is completely empty.

I'm suspecting the way they store things is quite a bit different from normal tabs.

Especially considering you can store 1 of all uniques in there and that makes up for a far larger grid than even a 4x sized super tab.

**Comment by Enlightnd** [comment]
After trying to use this all day, I've also found that the application doesn't update any of the inventories unless you restart it completely.

Refresh from within the application doesn't work.

**Comment by Stickymaddness** [comment]
[Procurement 1.27.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.27.2) has been released, which includes a number of refresh related fixes. Please test again and see if you still have issues.

**Comment by Enlightnd** [comment]
Seems to work so far.

Will report any further bugs I find.
