### ISSUE TITLE
Error Cloud flare 

### ISSUE THREAD

**Issue by HarkMorun** [Stickymaddness/Procurement#1104]
### **I used it for 5 days and now it doesn't work anymore. Update to the latest version, change the SsID to a new one and wait one day. still not working**

[22-04-2020 13:45] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': Error en el servidor remoto: (503) Servidor no disponible.
[22-04-2020 13:45] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: Se han producido uno o varios errores. ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 3 attempt(s).
   en CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   en POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   en POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
   en Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   en System.Threading.Tasks.Task.Execute()

**Comment by thailyn** [comment]
It looks like CloudFlare changed their authentication process again (GGG uses CloudFlare for handling authentication on their website and on the API).  The library Procurement uses appears to be working on a solution.  I'll follow up with it when I get a chance, and create a patched version of Procurement, as I did with the last change.

**Comment by HarkMorun** [comment]
thank you very much for the work and the inconvenience

**Comment by ifkvothe** [comment]
yesterday I was able to login but today it definitely doesn't work

**Comment by Monisssska** [comment]
I have the same problem since yesterday it does not work.

**Comment by leoclaro** [comment]
I have the same problem since yesterday it does not work too.

**Comment by HarkMorun** [comment]
https://github.com/Stickymaddness/Procurement/issues/1104#issuecomment-617909950

**Comment by Algosistaken** [comment]
I have the same problem. It was very good program for trading. Please fix it.

**Comment by ZakDolan** [comment]
Same problem here with the same timing.

**Comment by thailyn** [comment]
There is a new version of a fork of the Cloudflare library Procurement uses that appears to resolve this issue (I tested it and I can log in).  I've updated my patched version of Procurement in #1093 to use it.  You can download an updated version of Procurement at [this link](https://ci.appveyor.com/api/buildjobs/fx32dtcsod4aqknk/artifacts/Procurement%2Fbin%2FProcurement.zip). (Valid for six months from now.)

**Comment by Monisssska** [comment]
it work! thx :)

**Comment by kevinloh** [comment]
I tried thailyn's version of Procurement. While it didn't give the Cloud Flare error, it gave this error instead:
[Error] One or more errors occurred.

Found this in DebugInfo.log:

[12-05-2020 20:43] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[12-05-2020 20:43] System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   at CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   at CloudflareSolverRe.Solvers.JsChallengeSolver.<SolveChallenge>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by thailyn** [comment]
Hey, @kevinloh, that looks like an error that is fixed with the latest patched version I created (it's confusing, since I've made at least three patched versions).  Please try the version of Procurement you can download from the initial description in PR #1093, and let us know if you continue to have issues.  Thanks!

**Comment by kevinloh** [comment]
That worked! Thank you.

**Comment by Stickymaddness** [comment]
[Procurement 1.29.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0) has been released, which includes @thailyn's fixes as per the build he provided above.
