### ISSUE TITLE
Procurement not working

### ISSUE THREAD

**Issue by poplo892** [Stickymaddness/Procurement#1106]
Getting the following error in the debug: 

[01-05-2020 14:23] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': O servidor remoto devolveu um erro: (503) Servidor não disponível.
[01-05-2020 14:23] System.AggregateException: Ocorreram um ou mais erros. ---> System.FormatException: Cadeia de caracteres de entrada com formato incorrecto.
   em System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   em CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   em CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   em System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   em CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   em CloudflareSolverRe.Solvers.JsChallengeSolver.<SolveChallenge>d__7.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.Solvers.JsChallengeSolver.<Solve>d__6.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<SolveJavascriptChallenge>d__35.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em CloudflareSolverRe.CloudflareSolver.<SolveWithJavascript>d__33.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__32.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__31.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.Utilities.SemaphoreLocker.<LockAsync>d__1`1.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__30.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.ClearanceHandler.<GetClearance>d__24.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- Fim do rastreio da pilha de excepção interna ---
   em System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   em POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   em POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   em POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()
---> (Excepção Interna #0) System.FormatException: Cadeia de caracteres de entrada com formato incorrecto.
   em System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   em CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   em CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   em System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   em CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   em CloudflareSolverRe.Solvers.JsChallengeSolver.<SolveChallenge>d__7.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.Solvers.JsChallengeSolver.<Solve>d__6.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<SolveJavascriptChallenge>d__35.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em CloudflareSolverRe.CloudflareSolver.<SolveWithJavascript>d__33.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__32.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__31.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.Utilities.SemaphoreLocker.<LockAsync>d__1`1.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.CloudflareSolver.<Solve>d__30.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.ClearanceHandler.<GetClearance>d__24.MoveNext()
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()<---

**Comment by thailyn** [comment]
There is a 503 error from GGG, so this might be a transient error on their part.  Have you been able to log in previously?  Also, make sure you are using my latest patched version, available [here](https://github.com/Stickymaddness/Procurement/issues/1104#issuecomment-619186336).

**Comment by poplo892** [comment]
yap using the patched version :) 
On the Forum thread there are others complaining, so I suspect that it's an error that is affecting more people.

**Comment by Elfy** [comment]
Same for me, worked till this morning, then 503. And still not working 12h later.

[02-05-2020 2:29] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[02-05-2020 2:29] System.AggregateException: One or more errors occurred. ---> System.Exception: Error parsing JS challenge html
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Parse(String html, Uri siteUrl)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.<SolveChallenge>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.<Solve>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<SolveJavascriptChallenge>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<SolveWithJavascript>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.Utilities.SemaphoreLocker.<LockAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<GetClearance>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Exception: Error parsing JS challenge html
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Parse(String html, Uri siteUrl)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.<SolveChallenge>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.<Solve>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<SolveJavascriptChallenge>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<SolveWithJavascript>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.Utilities.SemaphoreLocker.<LockAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.CloudflareSolver.<Solve>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<GetClearance>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()<---

**Comment by poplo892** [comment]
@thailyn any luck getting through the root of this problem? Seems to be affecting a considerable amount of people. I'm just asking bc you managed to do the cloudflare quickfix.

**Comment by thailyn** [comment]
It looks like this might be yet another Cloudflare change that is causing an issue.  A new version of the Cloudflare library we use was released today.  I'll test it out and update my patched version if it works.

**Comment by thailyn** [comment]
I've tested this new library version and it appears to work, so I have updated my patched version of Procurement to use it.  You can download it [here](https://ci.appveyor.com/api/buildjobs/dnk13q6sxtt28yhd/artifacts/Procurement%2Fbin%2FProcurement.zip).  As before, this download will work for six months (until Nov. 3rd).

**Note:** Using this new version of the Cloudflare library required updating a bunch of other libraries Procurement uses.  Procurement appears to work fine, but I have not given it a thorough test yet.  Please let me know if there are any issues.

**Comment by poplo892** [comment]
Working fine thanks to your fix! thanks!

**Comment by Stickymaddness** [comment]
[Procurement 1.29.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0) has been released, which fixes this issue.
