### ISSUE TITLE
"Error getting items for league, are you sure your league settings are correct?"

### ISSUE THREAD

**Issue by MacNerm** [Stickymaddness/Procurement#114]
DebugInfo:

[25-05-2015 13:45] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-05-2015 13:45] Application Version: Procurement 1.9.2
[25-05-2015 13:45] 
CurrentCulture: en-SG
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[25-05-2015 13:45] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Im currently running POE through Garena+, is this an issue?

**Comment by Stickymaddness** [comment]
Yes, unfortunately Garena is not currently supported in Procurement.
