### ISSUE TITLE
Error downloading stash for Hardcore

### ISSUE THREAD

**Issue by NeverAgain** [Stickymaddness/Procurement#132]
~~~~
[20-07-2015 13:25] Error downloading stash for Hardcore, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[20-07-2015 13:25] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
~~~~

got this error after downloaded the newest procurement. I was using 1.9.2 and it was fine.

**Comment by Stickymaddness** [comment]
Are you still experiencing this issue?

**Comment by NeverAgain** [comment]
@Stickymaddness I used usersession ID to sign in instead now. but it just doesn't work with the username / password method.

**Comment by Stickymaddness** [comment]
It sounds like GGG is returning empty data when you use username/password for some reason. Interesting that it's fine with sessionID, they seem to be experiencing a lot of issues lately. 

Closing the issue since sessionID fixes your problem.
