### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by Quasar22227** [Stickymaddness/Procurement#139]
[Error] Error reading character data for <Name>, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
at System.Threading.Tasks.Task.Execute()

Help?

**Comment by Quasar22227** [comment]
Anyone?

**Comment by Quasar22227** [comment]
?

**Comment by Novarg** [comment]
Check account name. It is case sensitive

**Comment by dlcky** [comment]
having the same problem

**Comment by Stickymaddness** [comment]
Set Procurement to not download any characters and see if that helps, in your settings.xml set:

    <Setting name="DownloadOnlyMyCharacters" value="True" />

and make sure the character list is empty: 

    <List name="MyCharacters" />
