### ISSUE TITLE
Error loading Warbands Stash tabs, is inconsistent working only some of the time on clean reinstalls. 

### ISSUE THREAD

**Issue by RhaegarG** [Stickymaddness/Procurement#142]
This is the received error.
[27-07-2015 1:19] Error downloading stash for Warbands, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-07-2015 1:19] System.Exception: Downloading stash for Warbands, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
To confirm, are you saying that you are inconsistently getting this error, ie: some of the time your stash loads without any problems?

**Comment by RhaegarG** [comment]
When it loads without this error, it doesn't load all the tabs. It loads maybe the first 50, but after that they are all blank.

**Comment by Stickymaddness** [comment]
Have you / can you try logging in using sessionID
