### ISSUE TITLE
error in procurement

### ISSUE THREAD

**Issue by mephisto50** [Stickymaddness/Procurement#144]
[23-07-2015 20:32] System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[23-07-2015 20:34] Unknown character inventoryId 'Stash31' found for Totemic Maul
[23-07-2015 20:41] Unknown character inventoryId 'Stash31' found for Totemic Maul
[24-07-2015 13:24] Unknown character inventoryId 'Stash31' found for Totemic Maul
[25-07-2015 1:00] Unknown character inventoryId 'Stash31' found for Totemic Maul
[25-07-2015 17:21] Unknown character inventoryId 'Stash31' found for Totemic Maul
[26-07-2015 21:35] Unknown character inventoryId 'Stash31' found for Totemic Maul
[26-07-2015 22:35] Error refreshing tab: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.Stash.RefreshTab(POEModel currentModel, String currentLeague, Int32 tabId, String accountName)
[26-07-2015 22:36] Unknown character inventoryId 'Stash31' found for Totemic Maul
[27-07-2015 14:06] Unknown character inventoryId 'Stash31' found for Totemic Maul
[27-07-2015 18:10] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.postToForum(String data, String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[28-07-2015 3:17] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.postToForum(String data, String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[28-07-2015 3:19] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.postToForum(String data, String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[28-07-2015 14:49] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[28-07-2015 14:51] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[29-07-2015 2:25] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.postToForum(String data, String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:27] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:28] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[30-07-2015 20:28] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
[30-07-2015 20:28] JSON Serialization Failed: base64 bytes:
[30-07-2015 20:28] ZmFsc2U=
[30-07-2015 20:28] END
[30-07-2015 20:28] Error downloading stash for , exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[30-07-2015 20:28] System.Exception: Downloading stash for , details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The errors in the log are all related to issues on GGG's end, have you used Procurement before and logged in successfully, or are you a new user?
