### ISSUE TITLE
Expecting state 'Element'...Encountered 'Text' with name '', namespace '',

### ISSUE THREAD

**Issue by calipark** [Stickymaddness/Procurement#153]
Procurement doesn't want to load my characters.. I thought perhaps I would add something on hardcore tempest & standard to the stash just in case. Didn't work. Here's the debug info... Thank you!!!
"[06-08-2015 8:09] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at ReadArrayOfRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetCharacters()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()"

**Comment by calipark** [comment]
Problem seems to be with the "Medved" version of Procurement. Really wish it wouldn't claim to be more updated if it doesn't work.. Hmm. Works now with 1.9.3

**Comment by Stickymaddness** [comment]
I offer zero support for the "Medved" version as it is a modified version of Procurement. 

For support with this modified version you can log a ticket at https://github.com/medvedttn/Procurement/issues
