### ISSUE TITLE
MinmalMode setting not present causes Procurement to crash

### ISSUE THREAD

**Issue by ben-wallis** [Stickymaddness/Procurement#160]
When upgrading from 1.9.3 to 1.9.4 and copying over your old Settings.xml file, Procurement crashes as the MinmalMode setting did not exist in previous versions. Perhaps a check could be added to add missing settings at default values?

    <Setting name="MinimalMode" value="false" />

DebugInfo.log stack trace:

    [08-08-2015 22:56] System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Procurement.MainWindow' that matches the specified binding constraints threw an exception. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
    at Procurement.ViewModel.ScreenController..ctor(MainWindow layout)
    at Procurement.MainWindow..ctor()
    --- End of inner exception stack trace ---`

**Comment by Stickymaddness** [comment]
I considered adding a check for this, but beyond this release adding the check is a waste as from 1.9.4 everyone will have the settings, which is why I detailed that it needs to be manually added if you are using your old settings.xml file.

What I do plan on doing however is overhauling the settings code to be a lot more tolerant so that it will default any missing settings. The settings code has needed a refactoring for some time now.
