### ISSUE TITLE
[Error] There was an error deserializing the object

### ISSUE THREAD

**Issue by Ninnik** [Stickymaddness/Procurement#168]
Hello,
I have a problem when trying to start procurement:

Procurement 1.9.4 Initialized.
                                                           
Authenticating nxxxx.nxxx@xxx.de                                                        [OK]
Loading characters...                                                                     

[Error] There was an error deserializing the object of type System.Collections.Generic.List`1[[POEApi.Model.JSONProxy.Character, POEApi.Model, Version=1.9.4.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'.

The DebugInfo.log has following entry:

[14-08-2015 11:52] System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.Collections.Generic.List`1[[POEApi.Model.JSONProxy.Character, POEApi.Model, Version=1.9.4.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(XmlReaderDelegator reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetCharacters()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Hi,

The problem is that Procurement is getting back invalid data from GGG. Have you tried logging in with sessionID?

**Comment by Ninnik** [comment]
Thx for the reply.
I have not :-/
How does this SessionID thing work?

**Comment by Stickymaddness** [comment]
Take a look at this video https://www.youtube.com/watch?v=o8aHmbvWxAo There is also an article on the wiki if you need more detail.
