### ISSUE TITLE
Error getting items for  league, are yous ure your league settings are correct?

### ISSUE THREAD

**Issue by nenekoxkun** [Stickymaddness/Procurement#173]
first popup is the Error getting items for   league..... then the "There was an unhandled error - Sorry!" popup comes up. here is my debuginfo file.

I'm going to try the sessionID thing but I figured I'd go ahead and post this here.

[17-08-2015 11:55] Application Version: Procurement 1.9.4
[17-08-2015 11:55] 
CurrentCulture: en-US
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[17-08-2015 11:55] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.View.InventoryView..ctor()
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[17-08-2015 11:56] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User nenekoxkun@yahoo.com
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[17-08-2015 11:56] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User nenekoxkun@yahoo.com
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[17-08-2015 11:58] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[17-08-2015 11:58] Application Version: Procurement 1.9.4
[17-08-2015 11:58] 
CurrentCulture: en-US
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[17-08-2015 11:58] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.View.InventoryView..ctor()
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[17-08-2015 11:58] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[17-08-2015 11:58] Application Version: Procurement 1.9.4
[17-08-2015 11:58] 
CurrentCulture: en-US
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[17-08-2015 11:58] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.View.InventoryView..ctor()
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nenekoxkun** [comment]
UPDATE: tried the Session ID and I'm getting the same error.

**Comment by nenekoxkun** [comment]
UPDATE: tried moving the program to the drive where my POE is installed, still same error.

**Comment by nenekoxkun** [comment]
Hope I can get a response soon, I'd love to start using this program it seems really cool.

**Comment by Stickymaddness** [comment]
The error is due to GGG not returning any characters in any league(s) for your account. This sometimes happens with new accounts or steam accounts.

If you contact GGG support and tell them no character or item data is being returned by the API for your account, they will be able to address it for you.

**Comment by nenekoxkun** [comment]
All is well and working ty so much

**Comment by Stickymaddness** [comment]
No problem!
