### ISSUE TITLE
Thread Update not working

### ISSUE THREAD

**Issue by damoochie** [Stickymaddness/Procurement#179]
Hey, The Update Forum Thread feature isn't updating the thread even though it says it is. I restarted procurement to make sure it was updated and also made a new thread to see if that helped. No dice. I login with session ID using Firefox if that's of any import.

Thx

**Comment by damoochie** [comment]
Occasional error:

[23-08-2015 19:38] Error updating shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)

**Comment by Stickymaddness** [comment]
It looks like the update feature is timing out, GGG's servers seem to be rather unstable lately. 

Try see if you manually update your shop with something, and then try update with Procurement if you have any luck.

**Comment by damoochie** [comment]
Yeah unstable servers fits the shoe. I just managed to update my thread using procurement for the first time in about 4 days so at least it's not a program issue. Thanks
