### ISSUE TITLE
[23-08-2015 18:29] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by lexthirteen** [Stickymaddness/Procurement#181]
Hi, started to try and use Procurement for the first time and got this

[23-08-2015 18:29] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[23-08-2015 18:29] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

Any pointers appreciated.

**Comment by Stickymaddness** [comment]
Hi,

It looks like GGG is returning no items for your stash. Are you a steam user / have you tried logging in using sessionID ?

**Comment by lexthirteen** [comment]
Hi Sticky,

Apologies, I clocked that it was probably because I use Steam right after I posted! How embarrassing! Thanks for the hasty response regardless :)

**Comment by Stickymaddness** [comment]
Procurement supports steam, I just needed to check if you were/weren't a steam user.

The issue most likely is that your stash/items haven't properly been associated with your account, this is a fairly common issue with new steam users. You'll need to contact GGG support and let them know that the API is not returning any items for your account.

Once that's sorted you'll be able to login to Procurement

**Comment by lexthirteen** [comment]
Since I'm a Steam user I should be using the sessionid method though right? I'll try it and see if that gets it working

**Comment by lexthirteen** [comment]
Hi Sticky,

Used the SessionID message and my shop thread took seconds to make, Procurement is simply amazing! Thanks for making it.

**Comment by Stickymaddness** [comment]
Great stuff, glad you've found Procurement so helpful!
