### ISSUE TITLE
stash issue

### ISSUE THREAD

**Issue by shampoe** [Stickymaddness/Procurement#182]
[24-08-2015 21:13] Error downloading stash for Tempest, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[24-08-2015 21:13] System.Exception: Downloading stash for Tempest, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by shampoe** [comment]
fixed itself when i logged into a character in each league.
