### ISSUE TITLE
Error when updating hardcore stash tab

### ISSUE THREAD

**Issue by maphyr** [Stickymaddness/Procurement#189]
[02-09-2015 19:16] Error downloading stash for Hardcore, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-09-2015 19:16] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by sw0d** [comment]
how can i fix this?

**Comment by Stickymaddness** [comment]
Somehow this issue completely slipped past me, sorry! 

If you still have this issue, retest with Procurement 1.9.8-RC1 and open a new ticket with your debuglog if the error persists
