### ISSUE TITLE
Null Reference Exception preventing use

### ISSUE THREAD

**Issue by SayyadinaAtreides** [Stickymaddness/Procurement#193]
I've gotten this a number of times over the past couple of days; the first few times, restarting Procurement let it work, but not since this afternoon.

[07-09-2015 16:23] Error downloading stash for Warbands, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-09-2015 16:23] System.Exception: Downloading stash for Warbands, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Did you change any settings or anything, or did Procurement just suddenly start Procuring this error?
