### ISSUE TITLE
ItemFactory unable to instanciate type: Superior Pier Map. Crash on loading tab

### ISSUE THREAD

**Issue by hughesw** [Stickymaddness/Procurement#205]
Was cleaning up my stash in standard and one of my tabs with legacy maps on it is causing Procurement to blow up.

Here's the stack trace. This is from 1.9.5.
```
[02-10-2015 2:00] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Superior Pier Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-10-2015 2:00] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
```
I'll probably just chuck this thing in my guild bank and see if it proceeds afterwards, but I can test any fix for it by just pulling the item back.

**Comment by hughesw** [comment]
As an update, moving the old map just caused it to throw the same exception on a non-legacy map. I deleted Procurement's folder as well to make sure it wasn't some old stale data kicking around, and reinstalled from scratch. Unfortunately that didn't fix it.

**Comment by hughesw** [comment]
Looked through the code a bit out of curiosity. I'm betting the whole switchover to map tiers is what caused it. The error message printed is fairly generic and thrown if the specific type in ItemFactory throws an exception, and when I look at Map.cs it's looking for a line named "Map Level" to pull an int out of. That line isn't there anymore, it's now named "Map Tier".

I'm gonna look into what it takes to build this thing, unfortunately I don't have VS but if VS Express works it may be easy enough to just tweak the code in Map.

**Comment by Stickymaddness** [comment]
Yep you are correct, it's definitely due to the map changes. Unfortunately
this is what happens when developers give zero support to 3rd party devs.

Visual Studio community edition is a free download and will be able to
build Procurement.

I will do an official release with a fix as soon as I can.

**Comment by hughesw** [comment]
Quite sad, you'd think they could just create a pull request with the tweak to Map.cs and send it to you a couple days ahead of the patch, ideally with some sample JSON to use when updating tests. Considering how critical tools like Procurement and Acquisition are to the functioning of their game, that really should be something they do.

Oh well. Good to hear that the community version can build it. Gives me something to play around with for an hour or so at least.

**Comment by hughesw** [comment]
Alright well I can definitely confirm that changing "Map Level" to "Map Tier" in Map.cs works. It's successfully downloaded.

It's such a small change that I don't think it's worth tossing you a pull request for unless you want one. Particularly since you were already no doubt aware of the issue. I'm also guessing you probably want to do a more thorough refactor to change things like the MapLevel property to MapTier, so my little hack wouldn't help.

If there's anything I can do to help out, feel free to let me know, otherwise I'll look forward to replacing my homegrown build with the latest official.

**Comment by FixEd-It** [comment]
Yes, It's because of the changes to maps. I sold all my maps in Standard league, and now Procurement loads again. It will cost you all of your maps in Standard this way though. (I never play standard anymore, so I don't care :) )

**Comment by Moregaze** [comment]
Can someone give us a work around.  My store has been down since patch day

**Comment by Stickymaddness** [comment]
@hughesw If you have any new features/additions in your homegrown build that you feel would be a nice addition to Procurement, feel free to send me a pull request!

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
