### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by mroowke** [Stickymaddness/Procurement#215]
[02-10-2015 17:04] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[02-10-2015 17:04] ItemFactory unable to instanciate type : Reef Map
[02-10-2015 17:04] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Reef Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-10-2015 17:04] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by FixEd-It** [comment]
It's because of the changes to maps. I sold all my maps in Standard league, and now Procurement loads again. It will cost you all of your maps in Standard this way though. (I never play standard anymore, so I don't care :) )

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
