### ISSUE TITLE
error loading standard stash tabs 

### ISSUE THREAD

**Issue by insomniak99** [Stickymaddness/Procurement#217]
Procurement 1.9.5 Initialized.
                                                           
Authenticating craig.                                         [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[25-08-2015 11:17] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-08-2015 11:17] Application Version: Procurement 1.9.5
[25-08-2015 11:17] 
CurrentCulture: en-GB
CurrentUICulture: en-GB
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[25-08-2015 11:17] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-08-2015 11:18] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-08-2015 11:18] Application Version: Procurement 1.9.5
[25-08-2015 11:18] 
CurrentCulture: en-GB
CurrentUICulture: en-GB
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[25-08-2015 11:18] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-08-2015 11:23] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-08-2015 11:23] Application Version: Procurement 1.9.5
[25-08-2015 11:23] 
CurrentCulture: en-GB
CurrentUICulture: en-GB
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[25-08-2015 11:23] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-08-2015 11:26] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-08-2015 11:26] Application Version: Procurement 1.9.5
[25-08-2015 11:26] 
CurrentCulture: en-GB
CurrentUICulture: en-GB
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[25-08-2015 11:26] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-08-2015 11:37] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[25-08-2015 11:38] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[25-08-2015 11:38] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[25-08-2015 11:40] System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[25-08-2015 11:51] System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[25-08-2015 11:51] System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
