### ISSUE TITLE
Error downloading stash for hardcore

### ISSUE THREAD

**Issue by tehnew** [Stickymaddness/Procurement#221]
Procurement 1.9.5 Initialized.
                                                           
Authenticating iplay84@gmail.com                                                          [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading WoooooooE's inventory...                                                          [OK]
Loading Hardcore Stash Tab 1...                                                           [OK]
Loading Hardcore Stash Tab 2...                                                           [OK]
Loading Hardcore Stash Tab 4...                                                           [OK]
Loading Hardcore Stash Tab 6...                                                           [OK]
Loading Hardcore Stash Tab 7...                                                           [OK]
Loading Hardcore Stash Tab 8...                                                           [OK]
Loading Hardcore Stash Tab 9...                                                           [OK]
Loading Hardcore Stash Tab 10...                                                          [OK]
Loading Hardcore Stash Tab 11...                                                          [OK]

[Error] Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[02-10-2015 12:54] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[02-10-2015 12:54] ItemFactory unable to instanciate type : Thicket Map
[02-10-2015 12:54] Error downloading stash for Hardcore, exception details: System.Exception: ItemFactory unable to instanciate type : Thicket Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-10-2015 12:54] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
