### ISSUE TITLE
Can't download my character's inventory (not another map problem)

### ISSUE THREAD

**Issue by bratfizyk** [Stickymaddness/Procurement#249]
I've been trying to log in, but I was left with an error message and the app refused to perform a successfull log in.
Here's the content of DebugInfo:

[03-10-2015 21:17] Error reading character data for character '<char_name>', Exception info: 
[03-10-2015 21:17] System.Exception: Error reading character data for <char_name>, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by kuratsak** [comment]
same thing for me (standard), here is DebugInfo:
look at 03-10-2015 to get a fresh reproduction of the bug


[02-10-2015 20:12] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[02-10-2015 20:12] ItemFactory unable to instanciate type : Volcano Map
[02-10-2015 20:12] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Volcano Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-10-2015 20:12] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[03-10-2015 2:04] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 2:04] ItemFactory unable to instanciate type : Volcano Map
[03-10-2015 2:04] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Volcano Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-10-2015 2:04] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[03-10-2015 2:12] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 2:12] ItemFactory unable to instanciate type : Volcano Map
[03-10-2015 2:12] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Volcano Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-10-2015 2:12] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[03-10-2015 23:42] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 23:42] ItemFactory unable to instanciate type : Volcano Map
[03-10-2015 23:42] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Volcano Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-10-2015 23:42] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by bratfizyk** [comment]
Actually not really the same.
Your issue is known (take a look at few other today's issues) and it's due to the most recent changes to map system.

I followed the walkaround posted here:
https://github.com/Stickymaddness/Procurement/issues/239

but the new problem with loading my inventory appeared.

**Comment by saviola777** [comment]
Try to disable loading the character inventory by replacing

    <List name="MyCharacters">
      [...]
    </List>

with just

    <List name="MyCharacters" />

in the Settings.xml. If it works after that, it was something in your character's inventory that caused the error.

**Comment by bratfizyk** [comment]
Well... what if it doesn't work ? :)

**Comment by bratfizyk** [comment]
Hold on a second - I've just realized I messed up the account's name.
Sorry for the problem, but I admit the error message could have been more accurate.

**Comment by saviola777** [comment]
Then you probably have an error in your Settings.xml? Can you post the part starting with

    <Lists>
      [...]
    </Lists>
