### ISSUE TITLE
Map items not loading

### ISSUE THREAD

**Issue by coopshire** [Stickymaddness/Procurement#257]
Looks like there are a lot of maps not being loaded for some reason. I have removed several with this same string (destroyed) and I am not about to destroy the rest of my maps...

[05-10-2015 6:40] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[05-10-2015 6:40] ItemFactory unable to instanciate type : Catacomb Map
[05-10-2015 6:40] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Catacomb Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[05-10-2015 6:40] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Download the new version of Procurement 1.9.6 which came out yesterday, fixes this issue.

**Comment by coopshire** [comment]
I already did this. i am using 1.9.6

**Comment by coopshire** [comment]
I also want to note, those maps that are giving me problems are the old alternate maps styles they used before switching to the square looking maps

**Comment by Stickymaddness** [comment]
Interesting, I assume you've done a full update so all the tabs in your inventory have been redownloaded?

If so, can you zip and send me your .bin files. They will be in a folder with your email/alias.
