### ISSUE TITLE
Error loading stashtabs in standard

### ISSUE THREAD

**Issue by PopikBM** [Stickymaddness/Procurement#260]
Since it won't upload my text file,word or pdf(tried them all),posted the log here.

[07-10-2015 16:38] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-10-2015 16:38] ItemFactory unable to instanciate type : Bog Map
[07-10-2015 16:38] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Bog Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-10-2015 16:38] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by OG-OnlingGaming** [comment]
I also can not retrieve my stash tabs in standard.

**Comment by Stickymaddness** [comment]
Are you using the latest version of Procurement, 1.9.6?

**Comment by PopikBM** [comment]
nope

**Comment by Stickymaddness** [comment]
Then that's your issue.

**Comment by OG-OnlingGaming** [comment]
I am. 


     On Thursday, October 8, 2015 10:44 AM, Stickymaddness <notifications@github.com> wrote:
   

 Are you using the latest version of Procurement, 1.9.6? —

**Comment by OG-OnlingGaming** [comment]
Tried it again and now it may be working.
I had the same thing with the previous version. Initially it would not work so I made it only do warbands and then later it worked for standard too.
I think I have over 500 tabs in standard including the read only ones. 


     On Monday, October 12, 2015 8:27 AM, Ed Hamilton <onlinegaming@rogers.com> wrote:
   

 I am. 


     On Thursday, October 8, 2015 10:44 AM, Stickymaddness <notifications@github.com> wrote:
   

 Are you using the latest version of Procurement, 1.9.6? —

**Comment by Stickymaddness** [comment]
Weird. The GGG API has been acting up a lot lately, and returning invalid data for players. Glad you got it sorted.
