### ISSUE TITLE
[13-10-2015 19:56] System.Exception: Downloading stash for Standard

### ISSUE THREAD

**Issue by Remy85** [Stickymaddness/Procurement#263]
[13-10-2015 19:56] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at 
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

Any help would be awesome!

**Comment by Stickymaddness** [comment]
Hi there,

Is that the entirety of your debuglog ?
