### ISSUE TITLE
Downloading Stash for standard error on PC and Laptop V1.9.3

### ISSUE THREAD

**Issue by Axis-1** [Stickymaddness/Procurement#266]
Hi there

I've been unable to launch procurement due to the following error :

[20-10-2015 15:56] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[20-10-2015 15:56] ItemFactory unable to instanciate type : Strand Map
[20-10-2015 15:56] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Strand Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[20-10-2015 15:56] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Update to Procurement 1.9.6
