### ISSUE TITLE
Error Downloading stash

### ISSUE THREAD

**Issue by killingkong** [Stickymaddness/Procurement#311]
Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
[13-12-2015 23:36] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
