### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dirty1986** [Stickymaddness/Procurement#329]
[14-12-2015 19:37] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[14-12-2015 19:37] JSON Serialization Failed: base64 bytes:
[14-12-2015 19:37] ZmFsc2U=
[14-12-2015 19:37] END
[14-12-2015 19:37] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 19:37] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Are you logging in with sessionID? Have you checked that your account name is correct?

**Comment by dirty1986** [comment]
No im not using a session ID. Yes i have checked that my information is all correct.

**Comment by Judaspriester** [comment]
Hey,

first of all, im using the session id, ive already optained an new id, deleted and redownloaded the acutal version, but that all doesnt helped.
i thougt a little about when the problem has shown up. at sunday i bought the accendency package, and upgraded my stash tabs from normal to premium. then i got the problems at the next procurement login on monday.
so may it be possible that there is a problem with the named premium stash tabs? or maybe the fact that i still have some old racing tabs with legacy items, that get downloaded before the actual season tabs?

just some thoughts, but i hope they help to track down the problem.

**Comment by Stickymaddness** [comment]
@Judaspriester Thanks for the info, premium tabs shouldn't be a problem as Procurement has supported them for a long time. I know of a few streamers that use Procurement that have hundreds of named tabs.

It's possible however that old race tabs are causing a problem. What you could try is setting Procurement to only download the talisman league your are playing in.

Beyond that, I have created a wiki article which covers this issue, 

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Judaspriester** [comment]
Hey,
ive already seen ur wiki entry, but sadly it doesnt work for me. The deal with the racing tabs is, that they get still downloaded if i set it to only download talisman (even if they actually doesnt show up ingame). if i remember right they also show up before my common stash pages.
maybe i should realy think about cleaning them up.

**Comment by Judaspriester** [comment]
Hey,
for ur information, i solved the problem for me by picking up an session id via internet explorer in stead of firefox.
i dont know why, but it works.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
