### ISSUE TITLE
Issue downloading Standard Stash

### ISSUE THREAD

**Issue by ChubbyOwnz** [Stickymaddness/Procurement#333]
Tried with both standard Log-in and SessionID, I am a LONG time user, and have had zero issues. I see no thread posted with any fix but the issue has been going on for a while (Its been going on for at least 3-5 days for me), and I have downloaded any new updates to try and resolve the issue.

All replies I have seen from you are not fixes but just "try again", what's up?

[14-12-2015 5:40] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[14-12-2015 5:40] JSON Serialization Failed: base64 bytes:
[14-12-2015 5:40] ZmFsc2U=
[14-12-2015 5:40] END

**Comment by Stickymaddness** [comment]
Thanks for the info on your usage, it helps skip past the obvious stuff.

Basically, the error is that the GGG API is returning "false" instead of item data. In some cases this is due to a user error, eg: incorrect account name or rarer cases a firewall or AV blocking the request.

All other cases though, it's down to GGG's API being temperamental. Their API has become less and less stable in the last few months, and since I don't have access to it there's unfortunately nothing I can do other than say "try again".

Some users reported that logging out and back in to the forum helped, or getting sessionID from a different browser.

Take a look to see if your whole stash loads on the forum.

**Comment by ChubbyOwnz** [comment]
I will try all of this. I tried every browser that I could. I will log in and out and see what I can do. 


    On Tuesday, December 15, 2015 10:18 AM, Stickymaddness <notifications@github.com> wrote:
 

 Thanks for the info on your usage, it helps skip past the obvious stuff.Basically, the error is that the GGG API is returning "false" instead of item data. In some cases this is due to a user error, eg: incorrect account name or rarer cases a firewall or AV blocking the request.All other cases though, it's down to GGG's API being temperamental. Their API has become less and less stable in the last few months, and since I don't have access to it there's unfortunately nothing I can do other than say "try again".Some users reported that logging out and back in to the forum helped, or getting sessionID from a different browser.Take a look to see if your whole stash loads on the forum.—

**Comment by Stickymaddness** [comment]
I've created a wiki article around this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
