### ISSUE TITLE
[Error] Downloading stash for Talisman

### ISSUE THREAD

**Issue by XKogenX** [Stickymaddness/Procurement#337]
[Error] Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Debug contents are below.

[15-12-2015 15:21] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[15-12-2015 15:21] JSON Serialization Failed: base64 bytes:
[15-12-2015 15:21] ZmFsc2U=
[15-12-2015 15:21] END
[15-12-2015 15:21] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-12-2015 15:21] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[15-12-2015 15:22] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[15-12-2015 15:22] JSON Serialization Failed: base64 bytes:
[15-12-2015 15:22] ZmFsc2U=
[15-12-2015 15:22] END
[15-12-2015 15:22] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-12-2015 15:22] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by XKogenX** [comment]
I managed to solve this issue my self by searching through the forums. It was an issue with the Account Name. Thanks for your time.
