### ISSUE TITLE
error bumping shop thread 

### ISSUE THREAD

**Issue by xenochx** [Stickymaddness/Procurement#338]
can't bump shop threads since new install

[14-12-2015 21:35] Error bumping shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)
   at POEApi.Transport.HttpTransport.BumpThread(String threadID, String threadTitle)
[15-12-2015 17:20] Error bumping shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)

also note that update forum thread works successfully

**Comment by xenochx** [comment]
I completely remove the folder and created a new procurment folder and is working correctly now. Sorry I can't tell you anything more than that. Thanks for all the sweat and tears poured into this program!
