### ISSUE TITLE
[Error] Downloading stash for Talisman

### ISSUE THREAD

**Issue by whiteshark16** [Stickymaddness/Procurement#344]
Hi, I've been using version 1.9.7 without issue until several hours ago. Can you please help? Thanks a lot.

[16-12-2015 22:58] Error downloading stash for Talisman, exception details: System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at POEApi.Infrastructure.Extensions.ReadAllBytes(StreamReader reader)
   at POEApi.Transport.HttpTransport.getMemoryStreamFromResponse(HttpWebResponse response)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[16-12-2015 22:58] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/64236/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
That looks like a connection issue, have you checked for any connectivity issues or anything blocking Procurement?

**Comment by whiteshark16** [comment]
Hmm you're right, seems something blocked this connection. I was trying to restart my computer and network yesterday but it can't resolve. Then it suddenly work normally today. I will check the firewall rules next time if it happen again. Thanks, Sticky.

**Comment by Stickymaddness** [comment]
No problem!
