### ISSUE TITLE
[Error] Error reading character data.

### ISSUE THREAD

**Issue by harshnoisewall** [Stickymaddness/Procurement#347]
[17-12-2015 22:09] System.Exception: Error reading character data for GodlessTruth, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Take a look at https://github.com/Stickymaddness/Procurement/wiki/Error-reading-character-data-issue, you might still encounter another error which will be fixed in the new version of Procurement which will be out soon

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
