### ISSUE TITLE
Error downloading stash for Hardcore

### ISSUE THREAD

**Issue by Loktera** [Stickymaddness/Procurement#350]
[18-12-2015 14:16] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[18-12-2015 14:16] JSON Serialization Failed: base64 bytes:
[18-12-2015 14:16] ZmFsc2U=
[18-12-2015 14:16] END
[18-12-2015 14:16] Error downloading stash for Hardcore, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[18-12-2015 14:16] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
