### ISSUE TITLE
Issue finding league information - crashes while logging in

### ISSUE THREAD

**Issue by GitDMoT** [Stickymaddness/Procurement#360]
[26-12-2015 12:30] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[26-12-2015 12:30] Application Version: Procurement 1.9.8-RC1
[26-12-2015 12:30] 
CurrentCulture: en-US
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[26-12-2015 12:30] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.View.InventoryView..ctor()
   at Procurement.ViewModel.ScreenController.<initScreens>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GitDMoT** [comment]
I think this is something to do with my account and having no login information because it's a steam account.
