### ISSUE TITLE
'Nother "Error downloading stash for Standard" instance

### ISSUE THREAD

**Issue by DrakeCoker** [Stickymaddness/Procurement#369]
[01-01-2016 11:09] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 11:09] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
