### ISSUE TITLE
Error: (502) Bad Gateway.

### ISSUE THREAD

**Issue by shankapotimusrex** [Stickymaddness/Procurement#370]
I can't login using one of my Procurment programs....I have one for each shop thread. I have not changed any settings. 

This following is the output of the login screen;

- Procurement 1.9.7 Initialized.                                                           
- Authenticating shankapotimustex                                                           [OK]
- Loading characters...                                                                     [OK]
- Loading Standard Stash Tab 1...                                                        
- [Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

The following is the output of my debug log;

 [01-01-2016 11:07] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 11:07] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by shankapotimusrex** [comment]
The issue resolved without any action. Possible temporary network problem?
