### ISSUE TITLE
Error downloading stash (502) Bad Gateway.

### ISSUE THREAD

**Issue by Scarfinger68** [Stickymaddness/Procurement#394]
[02-01-2016 19:56] Error downloading stash for Hardcore, exception details: System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
