### ISSUE TITLE
Error Grabbing Hardcore stash

### ISSUE THREAD

**Issue by Exorm** [Stickymaddness/Procurement#403]
[03-01-2016 16:43] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

I don't even want the app to attempt opening my hardcore tabs anyways, since i do not play it. How do i turn it off? Since i have only made everything load one time.

Thanks

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

#397

Please follow this issue for updates and ask any questions there.
