### ISSUE TITLE
 Error downloading account name

### ISSUE THREAD

**Issue by Infiltrad0** [Stickymaddness/Procurement#407]
Hi, @Stickymaddness ,I have Procurement 1.9.8-RC1. But only once i could use this wonderfull app.

I'm using Session ID, because Steam.

I've done : "first log out of the forum, clear your cookies and then log back in using the POESESSID 

cookie to get your sessionID."

Here's the debug :

[04-01-2016 14:35] Error downloading account name, exception details: System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetAccountName()
[04-01-2016 14:35] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Hi @Infiltrad0,

When you say "only once i could use this wonderfull app" do you mean that you were able to login to Procurement once without any issues?

**Comment by Infiltrad0** [comment]
yes, i think this was 01-01-2016 . i've deleted folder and downloaded again a few times.

**Comment by Stickymaddness** [comment]
Ok, I think your issue is related to the load issues GGG have been experiencing lately. Issue #397 explains a bit about this issue.

Some users have reported that they have been able to login now, but it may depend on the current load on the server.

**Comment by Infiltrad0** [comment]
Hi, @Stickymaddness ... the soft don't work on xp ?

**Comment by Infiltrad0** [comment]
hi, @Stickymaddness i'm getting Error downloading account name, any idea why?

**Comment by Stickymaddness** [comment]
@Infiltrad0 I would check to see if you have any av/firewall/etc that might be blocking Procurement's connection to pathofexile.com

**Comment by Infiltrad0** [comment]
At first try, the new release is working, TNX!!!

**Comment by Infiltrad0** [comment]
At second try dosn´t work...

**Comment by Infiltrad0** [comment]
https://github.com/Stickymaddness/Procurement/issues/558

At 3rd comment i see the problem, my bad. :+1:
