### ISSUE TITLE
Error bumping thread operation timed out

### ISSUE THREAD

**Issue by 123qwet12** [Stickymaddness/Procurement#476]
here's the error snippet:

[05-02-2016 15:25] Error bumping shop thread: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.downloadPageData(String url)
   at POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)
   at POEApi.Transport.HttpTransport.BumpThread(String threadID, String threadTitle)

**Comment by Stickymaddness** [comment]
The thread updating/bumping is unfortunately not very reliable, there's not much I can do about timeouts currently.
