### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by Cubasmaster** [Stickymaddness/Procurement#481]
Cannot login, appears error above and then the file debugInfo shows this"[12-02-2016 21:38] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()"

**Comment by Stickymaddness** [comment]
Hmm, have you tried logging in with 1.9.7-RC1:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1 ?

**Comment by Cubasmaster** [comment]
Yes i have and worked fine :) thank´s

**Comment by Stickymaddness** [comment]
Great.
