### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by irvaine** [Stickymaddness/Procurement#499]
[05-03-2016 7:36] System.Exception: Downloading stash for Hardcore Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Have you tried logging in with Procurement 1.9.8-RC1?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

**Comment by irvaine** [comment]
Yes, same erro.


[05-03-2016 8:01] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[05-03-2016 8:01] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[05-03-2016 8:01] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[05-03-2016 8:01] ItemFactory unable to instanciate type : Perandus Coin
[05-03-2016 8:01] Error downloading stash for Hardcore Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at POEApi.Model.Stash.<.ctor>b__0(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[05-03-2016 8:01] System.Exception: Downloading stash for Hardcore Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Thanks for the second log, you can see the error is related to "Perandus Coin" which Procurement currently does not support.

I need to add support and release a new version which unfortunately may take a lot longer than the usual releases.

While not ideal, the best you can do until then if you want to use Procurement is to put your perandus coins in a separate tab and not download that tab with Procurement.

**Comment by irvaine** [comment]
OK, Ty;
