### ISSUE TITLE
Perandus error

### ISSUE THREAD

**Issue by ZackAttackHall** [Stickymaddness/Procurement#511]
below is the error file the program generated for me and told me to post here

[07-03-2016 1:36] Error reading character data for character 'actfourzackattackhall', Exception info: 
[07-03-2016 1:36] System.Exception: Error reading character data for actfourzackattackhall, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 1:36] Error reading character data for character 'actfourzackattackhall', Exception info: 
[07-03-2016 1:36] System.Exception: Error reading character data for actfourzackattackhall, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 1:38] Error reading character data for character 'actfourzackattackhall', Exception info: 
[07-03-2016 1:38] System.Exception: Error reading character data for actfourzackattackhall, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 1:39] Error reading character data for character 'actfourzackattackhall', Exception info: 
[07-03-2016 1:39] System.Exception: Error reading character data for actfourzackattackhall, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 1:40] Error reading character data for character 'actfourzackattackhall', Exception info: 
[07-03-2016 1:40] System.Exception: Error reading character data for actfourzackattackhall, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 1:41] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[07-03-2016 1:41] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[07-03-2016 1:41] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-03-2016 1:41] ItemFactory unable to instanciate type : Perandus Coin
[07-03-2016 1:41] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-03-2016 1:41] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please see issue #506 on how to get around this error until a new release of Procurement is available.
