### ISSUE TITLE
 [Error] Downloading stash for Hardcore Perandus[Please Help]

### ISSUE THREAD

**Issue by immaKulate** [Stickymaddness/Procurement#517]
I am a new user to Procurement and POE in general, I just found out about using Procurement but I am having trouble initiating the program. Here is the debug log and error message I am getting. I downloaded the latest version of framework, running on Windows 7. Thanks very much for your help!

Procurement Version: Procurement.1.9.8-RC1

[07-03-2016 11:15] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[07-03-2016 11:15] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[07-03-2016 11:15] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-03-2016 11:15] ItemFactory unable to instanciate type : Perandus Coin
[07-03-2016 11:15] Error downloading stash for Hardcore Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-03-2016 11:15] System.Exception: Downloading stash for Hardcore Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Hi there,

The error is due to the new Perandus coins which we added to PoE. As you've seen if you have them in your stash it causes Procurement to crash.

Take a look at issue #506, which will explain how you can get around this error until a new version of Procurement is released, which supports the coins.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
