### ISSUE TITLE
[Error] Downloading stash for Standard - 1.9.8.-RC1

### ISSUE THREAD

**Issue by pr2s** [Stickymaddness/Procurement#519]
[07-03-2016 23:15] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[07-03-2016 23:15] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[07-03-2016 23:15] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-03-2016 23:15] ItemFactory unable to instanciate type : Perandus Coin
[07-03-2016 23:15] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-03-2016 23:15] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 23:17] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[07-03-2016 23:17] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[07-03-2016 23:17] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-03-2016 23:17] ItemFactory unable to instanciate type : Perandus Coin
[07-03-2016 23:17] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-03-2016 23:17] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 23:18] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[07-03-2016 23:18] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[07-03-2016 23:18] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[07-03-2016 23:18] ItemFactory unable to instanciate type : Perandus Coin
[07-03-2016 23:18] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-03-2016 23:18] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[07-03-2016 23:20] Error downloading account name, exception details: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[07-03-2016 23:20] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[08-03-2016 0:20] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[08-03-2016 0:20] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[08-03-2016 0:20] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[08-03-2016 0:20] ItemFactory unable to instanciate type : Perandus Coin
[08-03-2016 0:20] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[08-03-2016 0:20] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[08-03-2016 0:20] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[08-03-2016 0:20] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[08-03-2016 0:20] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[08-03-2016 0:20] ItemFactory unable to instanciate type : Perandus Coin
[08-03-2016 0:20] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[08-03-2016 0:20] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by pr2s** [comment]
fixed

**Comment by Stickymaddness** [comment]
If you get this error again, please see issue #506 on how to get around this error until a new release of Procurement is available.
