### ISSUE TITLE
Cant retrive my stash

### ISSUE THREAD

**Issue by snakzz** [Stickymaddness/Procurement#524]
Hey,

I cant retrive my stash in perandus league :(

Whats the code that need to be used?

I am using 1, 2, 3 and normal as tab names.

    <List name="MyTabs">
      
      <Item value="Tab1" />
      <Item value="Tab2" />
      <Item value="Tab4" />
    </List>

I changed this because of the perandus coin error.

**Comment by Stickymaddness** [comment]
What error do you get when you try login? Delete your existing debug file so that a new one gets created, and try login again.

**Comment by snakzz** [comment]
[08-03-2016 15.00] System.InvalidOperationException: Sekvensen inneholder ingen samsvarende elementer
   ved System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   ved POEApi.Model.ProxyMapper.GetOrbType(String name)
[08-03-2016 15.00] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[08-03-2016 15.00] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   ved POEApi.Model.ProxyMapper.GetOrbType(String name)
   ved POEApi.Model.Currency..ctor(Item item)
   ved POEApi.Model.ItemFactory.Get(Item item)
[08-03-2016 15.00] ItemFactory unable to instanciate type : Perandus Coin
[08-03-2016 15.00] System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   ved POEApi.Model.ItemFactory.Get(Item item)
   ved System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   ved System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   ved System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   ved POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   ved Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   ved Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   ved System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   ved System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   ved Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   ved System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
It's failing because the tab Procurement is trying to load has coins in it:

    [08-03-2016 15.00] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin

It's possible that the website hasn't updated with the coins being moved to the new tab, you can check this on the forum.

Another possible solution would be to put your coins in a guild tab.

**Comment by snakzz** [comment]
Well, I dont even have an guild and guild tab :(

How can I exclude the tab that the coins are in?

**Comment by snakzz** [comment]
-<List name="MyTabs">







</List>

What do I need to change it with here to open my normal stash tabs?

I have no extra stash or anything.

I wanna place my coins in tab 4 and just exclude that.

**Comment by snakzz** [comment]
Anyone? :)

**Comment by Stickymaddness** [comment]
Take a look at issue #506 which has an example settings.xml

**Comment by snakzz** [comment]
I have tried to tell you many times i tror that code, but it would not open any of the tabs in my stash then.

So shop1 is the name of the tab1? The standard name? Because it aint able to pull it up.

**Comment by snakzz** [comment]
I tried to change the code to:
`    <List name="MyTabs">
      
      
      <Item value="1" />
      <Item value="2" />
    </List>`

But then I get this debug error:


[09-03-2016 12:17] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 12:17] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 12:17] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 12:17] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 12:17] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 12:17] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 12:23] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 12:23] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 12:23] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 12:23] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 12:23] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 12:23] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 12:23] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Your settings file looks correct, but it is still downloading a tab with coins in it. Do you have coins in the first tab? You need to put your Perandus coins in a tab that is excluded from your settings file, and it cannot be the first tab.

**Comment by snakzz** [comment]
I have my coins in the third tab..

But for some reason it still try to fetch the perandus stash tab 3 when trying to fetch even with that code in settings?

**Comment by Stickymaddness** [comment]
Hmm ok. 

Try this, load up your stash on the forum, and make sure that none of the coins are in your other tabs - sometimes the website doesn't update with your changes in game.

Just to check, are your tab settings correctly formatted in your settings file, ie:

```xml
<List name="MyTabs">
    <!--If you only want Procurement to download specific tabs list them here, eg :--> 
        <!--<Item value="Shop" />--> 
        <Item value="1" /> 
        <Item value="2" /> 
    </List>
```

and not everything on one line?

**Comment by snakzz** [comment]
This is how it looks like:

`    <List name="MyTabs">
      
      
      <Item value="1" />
      <Item value="2" />
    </List>`

I tried to change it to:

`    <List name="MyTabs">
      
      
      <Item value="Perandus-stash-1" />
      <Item value="Perandus-stash-2" />
    </List>`

What are the actual name for my stash tab on perandus?

Are they the same as the ones on standard?

**Comment by Stickymaddness** [comment]
I'm assuming you have the default tabs named 1, 2, 3,4 and not premium tabs? You then need to make the names 1, 2, 3, etc.

However, the formatting of your xml is incorrect, everything needs to be on a separate line:

```xml
<List name="MyTabs">
    <Item value="1" /> 
   <Item value="2" />
</List>
```
and NOT:
```xml
<List name="MyTabs"><Item value="1" /><Item value="2" /></List>
```

**Comment by snakzz** [comment]
They are in seperate lines in my file, its just the pasting here that dont work lol.

**Comment by Stickymaddness** [comment]
Ok great, just wanted to make sure about that.

So to confirm, you have it laid out correctly with the names as 1, 2, etc and it still crashes?

Have you checked on the forum that it's not displaying any coins for your stash?

**Comment by snakzz** [comment]
Will check in some hours, had to go to work :)

Thanks for the help so far :)

**Comment by Stickymaddness** [comment]
No problem, we'll get this sorted!

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
