### ISSUE TITLE
error downloading stash for perandus

### ISSUE THREAD

**Issue by unknown513** [Stickymaddness/Procurement#533]
[09-03-2016 16:32] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User mikekim513@gmail.com
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 16:33] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 16:33] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 16:33] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 16:33] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 16:33] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 16:33] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 16:34] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 16:34] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 16:34] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 16:34] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 16:34] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 16:34] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 16:36] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 16:36] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 16:36] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 16:36] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 16:36] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 16:36] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[09-03-2016 16:58] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-03-2016 16:58] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[09-03-2016 16:58] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[09-03-2016 16:58] ItemFactory unable to instanciate type : Perandus Coin
[09-03-2016 16:58] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-03-2016 16:58] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please see issue #506 on how to get around this error until a new release of Procurement is available.
