### ISSUE TITLE
Error downloading account name

### ISSUE THREAD

**Issue by DiegoSPB** [Stickymaddness/Procurement#541]
[11-03-2016 11:51] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Have you tried Procurement 1.9.8-RC2 ?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC2

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
