### ISSUE TITLE
[Error] Downloading stash for Perandus

### ISSUE THREAD

**Issue by kemikliet** [Stickymaddness/Procurement#553]
Procurement 1.9.7 Initialized.
                                                           
Authenticating xxxxxxxx                                                               [OK]
Loading characters...                                                                     [OK]
Loading Perandus Stash Tab 1...                                                           [OK]

[Error] Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[17-03-2016 10:54] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[17-03-2016 10:54] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[17-03-2016 10:54] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[17-03-2016 10:54] ItemFactory unable to instanciate type : Perandus Coin
[17-03-2016 10:54] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-03-2016 10:54] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
1.9.8-RC2 will fix your specific issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC2

Note that you might still run into issues due to ascendancy changes, which will be fixed soon in the next release.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
