### ISSUE TITLE
Procurement doesn't refresh tabs correctly

### ISSUE THREAD

**Issue by s1423** [Stickymaddness/Procurement#557]
[19-03-2016 13:45] Error refreshing tab: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.Stash.RefreshTab(POEModel currentModel, String currentLeague, Int32 tabId, String accountName)

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
