### ISSUE TITLE
Exception while downloading hardcore stash

### ISSUE THREAD

**Issue by Klim314** [Stickymaddness/Procurement#560]
[20-03-2016 11:17] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by hakkotsu** [comment]
You should upload debuginfo.log file

**Comment by Klim314** [comment]
Uploaded as txt as .log file not accepted.
[DebugInfo.log.txt](https://github.com/Stickymaddness/Procurement/files/181186/DebugInfo.log.txt)

**Comment by hakkotsu** [comment]
Looks like you are using session Id for login and it was invalidated, try to set a new one or login with login/password

**Comment by Klim314** [comment]
Errors occurred before sessionid. Sessionid error is there because I was
wondering what it was.
