### ISSUE TITLE
Procurement not searching

### ISSUE THREAD

**Issue by DesperadoJay** [Stickymaddness/Procurement#565]
May have broken with my buying of currency tab.
Here is the debug text:

[24-03-2016 11:45] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.Controls.StashControl.ForceUpdate()
   at Procurement.ViewModel.StashViewModel.processFilter()
   at Procurement.ViewModel.StashViewModel.SetCategoryFilter(String category, Nullable`1 isChecked)
   at Procurement.View.StashView.CheckBox_Checked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ToggleButton.OnToggle()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hippowind** [comment]
the same problem after buying currency stash

**Comment by OlympicLarry** [comment]
Temp fix to get search working, look in StashControl.xaml.cs line 41. Put updateResult in a try catch.

    try
    {
        updateResult(borderByLocation[Tuple.Create<int, int>(item.X, item.Y)], search(item));
    }
    catch {}


This does not fix the underlying issue with the new currency stash, it just lets the search continue.

**Comment by damoochie** [comment]
Search also not working after currency tab added. Can you please give more details on this workaround? I cant find 'StashControl'....

**Comment by OlympicLarry** [comment]
Sorry, I should have explained that better. You would have to download the source and find that file to update. Its really only a solution if you have Visual Studio 2013.

**Comment by damoochie** [comment]
I have notepad? xD Thanks for response anyway.

**Comment by Stickymaddness** [comment]
Can someone supply me with their .bin files which contain a currency tab, so that I can take a look.

**Comment by DesperadoJay** [comment]
here you go....

opps github says it doesn't support the attachment of .bin files.
Sent as email

**Comment by damoochie** [comment]
I'll gladly do this if still needed.. but how to send it to you? I have dropbox...

**Comment by damoochie** [comment]
Any word of a fix yet? Missing the search function a lot.

**Comment by OlympicLarry** [comment]
You could download the free visual studio version and compile the source with the change I suggested. My workaround fix is working for all tabs except the new currency tab.

https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by damoochie** [comment]
I'm in over my head with this i think. I managed to edit line 41 within visual studio but it has errors when saving and i'm not sure how to export it all as an exe. Can you share your compiled version somehow? Thx for your effort

**Comment by OlympicLarry** [comment]
https://dl.dropboxusercontent.com/u/12262/Procurement.exe

**Comment by damoochie** [comment]
It's working! Thank you so much! I don't have the nouse to do any of that nefarious stuff you mentioned so don't worry lol

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

If any of you experience further issues with 1.9.9, please open a new separate ticket.
