### ISSUE TITLE
Error when bumping thread.

### ISSUE THREAD

**Issue by jarekb84** [Stickymaddness/Procurement#57]
Bumping worked fine the before, but just got this error when trying to bump my forum shop thread. Updating the thread works fine though.

	Unknown character inventoryId 'Stash13' found for Transmutation ShardError in EquipedItems.setProperty : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at POEApi.Model.EquipedItems.setProperty(Item item)Target property : CursorUnknown character inventoryId 'Stash13' found for Gold AmuletError in EquipedItems.setProperty : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at POEApi.Model.EquipedItems.setProperty(Item item)Target property : CursorUnknown character inventoryId 'Stash13' found for ChainUnknown character inventoryId 'Stash13' found for Alteration ShardError updating shop thread: System.Net.WebException: The operation has timed out
	   at System.Net.HttpWebRequest.GetResponse()
	   at POEApi.Transport.HttpTransport.downloadPageData(String url)
	   at POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)System.Net.WebException: The remote name could not be resolved: 'www.pathofexile.com'
	   at System.Net.HttpWebRequest.GetResponse()
	   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
	   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
	   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
	   at System.Threading.Tasks.Task.Execute()System.Net.WebException: The remote name could not be resolved: 'www.pathofexile.com'
	   at System.Net.HttpWebRequest.GetResponse()
	   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
	   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
	   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
	   at System.Threading.Tasks.Task.Execute()Error bumping shop thread: System.Net.WebException: The operation has timed out
	   at System.Net.HttpWebRequest.GetResponse()
	   at POEApi.Transport.HttpTransport.downloadPageData(String url)
	   at POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)
	   at POEApi.Transport.HttpTransport.BumpThread(String threadID, String threadTitle)Error bumping shop thread: System.Net.WebException: The operation has timed out
	   at System.Net.HttpWebRequest.GetResponse()
	   at POEApi.Transport.HttpTransport.downloadPageData(String url)
	   at POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)
	   at POEApi.Transport.HttpTransport.BumpThread(String threadID, String threadTitle)

**Comment by Stickymaddness** [comment]
This should be fixed in the latest Procurement, open a new ticket if you still have issues.
