### ISSUE TITLE
Cannot load stash tabs for 2 days - debug error

### ISSUE THREAD

**Issue by RookieMaroK** [Stickymaddness/Procurement#580]
[03-04-2016 11:33] Error downloading stash for Standard, exception details: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-04-2016 11:33] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2016 17:15] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2016 17:18] Error downloading stash for Standard, exception details: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-04-2016 17:18] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2016 18:07] Error downloading stash for Perandus, exception details: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-04-2016 18:07] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
