### ISSUE TITLE
Trojan, 1.9.8 damaged archive, 1.9.7 error DLing stash

### ISSUE THREAD

**Issue by vemonster** [Stickymaddness/Procurement#587]
First download 360 Security found a trojan in your 1.9.8 zip and quarantined it. The second download cleared my antivirus but encountered this error when extracting with winrar: 'The archive is either in unknown format or damaged' . Never had these problems extracting anything in the past.. Not sure what the issue it.

I tried DLing 1.9.7 and it worked fine, so i am using that atm. Except when I logged in and it was loading my stash i received another error:

Loading characters...                                                                     [OK]
Loading Perandus Stash Tab 1...                                                           [OK]

[Error] Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Debuginfo.log:**

[16-04-2016 12:01] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[16-04-2016 12:01] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[16-04-2016 12:01] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
   at POEApi.Model.Currency..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[16-04-2016 12:01] ItemFactory unable to instanciate type : Perandus Coin
[16-04-2016 12:01] Error downloading stash for Perandus, exception details: System.Exception: ItemFactory unable to instanciate type : Perandus Coin
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[16-04-2016 12:01] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
