### ISSUE TITLE
failed to load stops at 240

### ISSUE THREAD

**Issue by juncraul** [Stickymaddness/Procurement#602]
Hello it fails to load all stash tab. It stops at 240, not sure if that is the maximum it can handle or I have something special in that tab, I use Procurement 1.9.9

Thanks for help

[02-06-2016 22:10] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[02-06-2016 22:10] JSON Serialization Failed: base64 bytes:
[02-06-2016 22:10] ZmFsc2U=
[02-06-2016 22:10] END
[02-06-2016 22:10] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-06-2016 22:10] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
240 tabs shouldn't be the maximum, I know there are Procurement users that have more.

The error is that you're getting empty data back from GGG, are there any old race characters or characters that you haven't logged into in a long time in that league?
