### ISSUE TITLE
Error downloading stash for standard

### ISSUE THREAD

**Issue by Eldena** [Stickymaddness/Procurement#619]
[07-09-2016 16:12] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()

**Comment by Stickymaddness** [comment]
Please test with the new version of Procurement and open a new issue if the error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.10.0
