### ISSUE TITLE
cant log in 1.10

### ISSUE THREAD

**Issue by Grubby85** [Stickymaddness/Procurement#628]
[01-10-2016 21:44] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.11.0 has been released, please open a new ticket if you run into further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
