### ISSUE TITLE
Error Launching Procurement

### ISSUE THREAD

**Issue by dannn310** [Stickymaddness/Procurement#645]
[04-12-2016 1:11] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-12-2016 1:11] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.11.0 has been released, please retest and open a new ticket if you have any further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
