### ISSUE TITLE
Downloading stash (breach) error

### ISSUE THREAD

**Issue by DBKotor** [Stickymaddness/Procurement#663]
DebugLog.log, please open a ticket at https://code.google.com/p/procurement/issues/list
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

I get to the point where it tries to load the stash of the character and fails with this error.

**Comment by Stickymaddness** [comment]
Please include your debuglog
