### ISSUE TITLE
Procurement Login Issue

### ISSUE THREAD

**Issue by PainfulGamer** [Stickymaddness/Procurement#677]
[09-03-2017 0:54] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[09-03-2017 0:54] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
