### ISSUE TITLE
Issue Downloading Stash

### ISSUE THREAD

**Issue by RSMurphy** [Stickymaddness/Procurement#681]
I was having issues getting Characters to load in Legacy league, so I tried loading a standard character and got an error downloading stash.

  at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)JSON Serialization Failed: base64 bytes:ZmFsc2U=ENDSystem.Exception: Downloading stash, details logged to DebugLog.log, please open a ticket at https://code.google.com/p/procurement/issues/list
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by RSMurphy** [comment]
This is the error I am getting trying to load my legacy league character.  

 at POEApi.Model.POEModel.GetInventory(String characterName)System.Exception: Error reading character data for Selectstar, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName)
   at Procurement.ViewModel.LoginWindowViewModel.loadCharacterInventory(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
