### ISSUE TITLE
Issues logging into account

### ISSUE THREAD

**Issue by LinusLindgren** [Stickymaddness/Procurement#685]
[20-03-2017 18:55] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by aydjay** [comment]
You need to make sure that you don't have any white space around your password cookie.
