### ISSUE TITLE
Error downloading account name

### ISSUE THREAD

**Issue by gregorianblack** [Stickymaddness/Procurement#688]
Hi trying to log on and it keeps saying error in account name

Debug log

03-04-2017 5:56] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

[03-04-2017 5:56] Application Version: Procurement 1.11.0
[03-04-2017 5:56] 
CurrentCulture: en-US
CurrentUICulture: en-US
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[03-04-2017 5:56] System.NullReferenceException: Object reference not set to an instance of an object.
   at Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   at Procurement.View.InventoryView..ctor()
   at Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[03-04-2017 15:04] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:06] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:06] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:06] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[03-04-2017 15:06] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:07] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[03-04-2017 15:07] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:07] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[03-04-2017 15:07] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[03-04-2017 15:09] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[03-04-2017 15:09] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by gregorianblack** [comment]
Resolved 


Figured it out

**Comment by aydjay** [comment]
If you wouldn't mind closing this issue - thanks,
