### ISSUE TITLE
Error downloading account name

### ISSUE THREAD

**Issue by snace29** [Stickymaddness/Procurement#689]
[04-04-2017 18:00] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:00] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:01] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:01] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:04] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:04] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:06] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:06] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:06] System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:07] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:07] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:12] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:12] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:17] Error downloading account name, exception details: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[04-04-2017 18:17] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[04-04-2017 18:19] System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
> The operation has timed out

This is a network related issue, are you sure a firewall or similar is not blocking Procurement from reaching pathofexile.com ?
