### ISSUE TITLE
error downloading acc name

### ISSUE THREAD

**Issue by kalin1518** [Stickymaddness/Procurement#691]
at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:51] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:51] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:55] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:55] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:57] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 3:47] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 3:47] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 3:56] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 4:18] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 18:17] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 18:17] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 18:18] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[13-04-2017 16:57] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:57] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:57] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:57] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:58] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:58] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:59] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:59] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:02] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:02] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:24] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:24] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()

**Comment by Stickymaddness** [comment]
Do you have a firewall or similar that might be blocking Procurement from connecting to pathofexile.com? The error is due to Procurement getting null data back when it asks for your account name.
