### ISSUE TITLE
error downloading account name

### ISSUE THREAD

**Issue by kalin1518** [Stickymaddness/Procurement#692]
[09-04-2017 1:44] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 1:45] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 1:46] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 1:46] System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 2:41] System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 2:41] System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 2:44] System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 2:44] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-04-2017 2:45] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[09-04-2017 2:53] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[09-04-2017 3:11] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[09-04-2017 3:15] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[10-04-2017 6:36] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[10-04-2017 6:37] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 2:51] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] System.Net.CookieException: The 'Value'='@Cyyera Hi, I would like to buy your level 19 20% Spark listed for 5 chaos in Standard (stash tab "For Sale"; position: left 11, top 9)' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.Add(Cookie cookie)
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] System.Net.CookieException: The 'Value'='@Cyyera Hi, I would like to buy your level 19 20% Spark listed for 5 chaos in Standard (stash tab "For Sale"; position: left 11, top 9)' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.Add(Cookie cookie)
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:51] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:51] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:51] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:55] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 2:55] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 2:57] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 3:47] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 3:47] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 3:56] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 4:18] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[12-04-2017 18:17] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[12-04-2017 18:17] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-04-2017 18:18] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[13-04-2017 16:57] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:57] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:57] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:57] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:58] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:58] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 16:59] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 16:59] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:02] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:02] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:24] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:24] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:29] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:29] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:30] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[13-04-2017 17:30] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[13-04-2017 17:31] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 0:30] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 0:53] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 0:53] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 0:53] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 4:02] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 4:58] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 4:58] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 19:16] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[14-04-2017 19:43] Error in StashControl.GetTabType: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Procurement.Controls.StashControl.GetTabType()
[19-04-2017 9:27] System.Net.CookieException: The 'Value'='Online game addiction is now the contemporary epidemic that is exploding across screens across the world and striking children, teenagers and even adults. Just like a virus computer gaming and online addiction is spreading rapidly for the last 15 years amongst out own pure age group and negatively impacting on their quality of life in so many was.' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.Add(Cookie cookie)
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[19-04-2017 9:28] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[19-04-2017 9:28] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[19-04-2017 9:28] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[19-04-2017 9:28] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[19-04-2017 9:28] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[19-04-2017 9:28] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[19-04-2017 9:28] Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   at POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   at POEApi.Model.POEModel.GetAccountName()
[19-04-2017 9:28] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please retest with [Procurement 1.12.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.12.0) which has just been released, and create a new issue if the problem persists.
