### ISSUE TITLE
Add proper Shard Support

### ISSUE THREAD

**Issue by aydjay** [Stickymaddness/Procurement#708]
See title

**Comment by SabreCat** [comment]
Possibly relevant? I can't seem to log in, and the error log has a bunch of complaints about shards:

```
[09-08-2017 10:36] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-08-2017 10:36] ProxyMapper.GetOrbType Failed! ItemType = Annulment Shard
[09-08-2017 10:36] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-08-2017 10:36] ProxyMapper.GetOrbType Failed! ItemType = Binding Shard
[09-08-2017 10:36] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POEApi.Model.ProxyMapper.GetOrbType(String name)
[09-08-2017 10:36] ProxyMapper.GetOrbType Failed! ItemType = Engineer's Shard
[09-08-2017 10:36] Error reading character data for character 'Eristeia', Exception info: 
[09-08-2017 10:36] System.Exception: Error reading character data for Eristeia, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[09-08-2017 10:36] Error reading character data for character 'Eristeia', Exception info: 
[09-08-2017 10:36] System.Exception: Error reading character data for Eristeia, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by aydjay** [comment]
Still very much relevant - i'll see what I can do to alleviate the problems.
