### ISSUE TITLE
Error setting tabwide buyout [1.9]

### ISSUE THREAD

**Issue by NotJordy** [Stickymaddness/Procurement#71]
When I try to set a tabwide buyout I get this error:

[13-01-2015 15:40] Exception in setTabBuyout_Click: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.setTabBuyout_Click(Object sender, RoutedEventArgs e)

**Comment by Stickymaddness** [comment]
Could you zip and send me your .bin files, so I can load them up and see what the issue is.

**Comment by firstgid** [comment]
i got similar problem.
[05-02-2015 17:42] Exception in setTabBuyout_Click: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Procurement.ViewModel.StashViewModel.setTabBuyout_Click(Object sender, RoutedEventArgs e)

**Comment by Stickymaddness** [comment]
Closing due to inactivity, please open a new ticket if this is still an issue!
