### ISSUE TITLE
Won't download stash for standard

### ISSUE THREAD

**Issue by Chommer** [Stickymaddness/Procurement#712]
[07-08-2017 18:28] Error in ProxyMapper.GetCharges: System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Object[]'.
   at POEApi.Model.ProxyMapper.GetCharges(List`1 list)
[07-08-2017 18:31] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[07-08-2017 18:31] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by aydjay** [comment]
Could you attach, from the application installation directory your bin files.

c:\appInstallDirectory\YourUsername\lotsOfBinFiles.bin

I will need all the files there so if you could zip them up that would be appreciated.

Thanks

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0) and create a new ticket if this is still an issue.
