### ISSUE TITLE
[Error] The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by TrevoraReeves** [Stickymaddness/Procurement#728]
This is what I get on startup of the application and try sync with my Stash tabs after making no alterations to the settings.
```
Procurement 1.1.1 Initialized.
                                                           
Authenticating cpchrome@yahoo.com               [OK]
Loading characters...                           [OK]
Loading TRangah's inventory...                  [ER]
Loading Standard Stash Tab 1...                                                           

[Error] The remote server returned an error: (403) Forbidden.
```
Here is the Debuginfo provided
```
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
```

Thanks for all of your work on this!!

**Comment by Stickymaddness** [comment]
Procurement 1.1.1 is ancient, update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0).
