### ISSUE TITLE
keep having problems initializing procurement application.

### ISSUE THREAD

**Issue by rar155** [Stickymaddness/Procurement#731]
here is the debuginfo log below.
it will stop at random points, sometimes get only a few tabs, sometimes many, sometimes all and then get stuck on another character in the same league. ive got no idea whats wrong.
i thought i might of had an outdated version, so i uninstalled procurement and installed current version but same thing continues.
i dont think its the sessid, cause it will load nearly all of the stash tabs before giving an error message.
please someone help me.

debunginfo log:
(i couldnt get it to attach for some reason)

[31-08-2017 16:28] Error in ProxyMapper.GetCharges: System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Object[]'.
   at POEApi.Model.ProxyMapper.GetCharges(List`1 list)
[31-08-2017 16:43] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[31-08-2017 16:43] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[31-08-2017 16:46] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[31-08-2017 16:46] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[31-08-2017 17:12] Error in ProxyMapper.GetCharges: System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Object[]'.
   at POEApi.Model.ProxyMapper.GetCharges(List`1 list)
[31-08-2017 17:33] Error reading character data for character 'Galirakath', Exception info: 
[31-08-2017 17:33] System.Exception: Error reading character data for Galirakath, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[31-08-2017 20:42] Error reading character data for character 'JoelPizzaDelivery', Exception info: 
[31-08-2017 20:42] System.Exception: Error reading character data for JoelPizzaDelivery, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[31-08-2017 21:19] Error in ProxyMapper.GetCharges: System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Object[]'.
   at POEApi.Model.ProxyMapper.GetCharges(List`1 list)
[31-08-2017 21:44] Error reading character data for character 'JoelPizzaDelivery', Exception info: 
[31-08-2017 21:44] System.Exception: Error reading character data for JoelPizzaDelivery, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by rar155** [comment]
think ive figured it out.
i had acquisition running at the same time as procurement, i think that was the issue.

**Comment by rar155** [comment]
ive got the original error message:

[Error] Error reading character data for Galirakath, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

Does anyone know why this is caused? it appears every time and will not let me load into procurement.

**Comment by rar155** [comment]
i finally loaded into procurement successfully, i had to change the settings to not load any of my characters inventories, then i closed procurement, deleted my current pathofexile cookies, open pathofexile again to get new cookies, and launched procurement with a new sessid, went to sleep, and woke up to find it finally working!!

**Comment by rar155** [comment]
but regardless i believe that this is the same issue that everyone else is having:
-error downloading name #730 
-error reading character data #725 
-error downloading account name #724 
-error reading character data for _DianWei_ , stash is ok #720 
-error reading character data #709
-expired name error #704 
and many many more of the same nature, please fix this or at least add it to an faq or ssomething

**Comment by GabrielFW** [comment]
How did you disable the characters inventories loading?

**Comment by driz** [comment]
I set a favoritecharacter and set DownloadOnlyMyCharacters to true and it loaded for me. Not sure what is causing the main issue, but hey, it's working.

**Comment by aydjay** [comment]
In the application installation folder there will be a folder with your profile name on it. Inside there will be a load of bin files. Can you please zip up the bin files for me and I will try and replicate and resolve this issue.

**Comment by Stickymaddness** [comment]
This should be fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)
