### ISSUE TITLE
Procurement error

### ISSUE THREAD

**Issue by theo1000** [Stickymaddness/Procurement#768]
[08-12-2017 23:53] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by theo1000** [comment]
sorry thats the full 1

[08-12-2017 23:53] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[08-12-2017 23:53] ItemFactory unable to instantiate type : The King's Blade
[08-12-2017 23:53] Error downloading stash for Standard, exception details: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[08-12-2017 23:53] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
