### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by zlobazla** [Stickymaddness/Procurement#78]
when i try to login... that just write [Error] Username or password incorrect. User ......

from debug info:
[14-02-2015 14:08] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User marian.kalman@gmail.com
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

i am insane from this i instal unistal it more then 10 times... poe reinstaled too but still nothing...

**Comment by Stickymaddness** [comment]
Do you use the exact same username and password to login to the game and forum? Have you tried using sessionID?

**Comment by Stickymaddness** [comment]
Closing due to inactivity, please open a new ticket if this is still an issue!
