### ISSUE TITLE
[Error] Downloading stash for Abyss

### ISSUE THREAD

**Issue by Enzo7777** [Stickymaddness/Procurement#787]
[11-12-2017 7:02] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 7:02] ItemFactory unable to instantiate type : Viridian Jewel
[11-12-2017 7:02] Error downloading stash for Abyss, exception details: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 7:02] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[11-12-2017 7:33] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 7:33] ItemFactory unable to instantiate type : Viridian Jewel
[11-12-2017 7:33] Error downloading stash for Abyss, exception details: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 7:33] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[11-12-2017 9:51] System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[11-12-2017 10:05] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 10:05] ItemFactory unable to instantiate type : Viridian Jewel
[11-12-2017 10:05] Error downloading stash for Abyss, exception details: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 10:05] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.

**Comment by Enzo7777** [comment]
thank you so much
