### ISSUE TITLE
[Error] Error reading character data for Character, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

### ISSUE THREAD

**Issue by Enzo7777** [Stickymaddness/Procurement#794]
[12-12-2017 0:32] System.InvalidCastException: Unable to cast object of type 'POEApi.Model.Gear' to type 'POEApi.Model.Gem'.
   at POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[12-12-2017 0:32] ItemFactory unable to instantiate type : Stygian Vise
[12-12-2017 0:32] Error reading character data for character 'SaK_Ma', Exception info: 
[12-12-2017 0:32] System.Exception: Error reading character data for SaK_Ma, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-12-2017 0:33] System.InvalidCastException: Unable to cast object of type 'POEApi.Model.Gear' to type 'POEApi.Model.Gem'.
   at POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[12-12-2017 0:33] ItemFactory unable to instantiate type : Stygian Vise
[12-12-2017 0:33] Error reading character data for character 'SaK_Ma', Exception info: 
[12-12-2017 0:33] System.Exception: Error reading character data for SaK_Ma, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[12-12-2017 0:34] System.InvalidCastException: Unable to cast object of type 'POEApi.Model.Gear' to type 'POEApi.Model.Gem'.
   at POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[12-12-2017 0:34] ItemFactory unable to instantiate type : Stygian Vise
[12-12-2017 0:34] Error reading character data for character 'SaK_Ma', Exception info: 
[12-12-2017 0:34] System.Exception: Error reading character data for SaK_Ma, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.
