### ISSUE TITLE
Issue in 1.18.0

### ISSUE THREAD

**Issue by TardisMaximus** [Stickymaddness/Procurement#795]
As others have reported, having an issue with the new release (1.17.0 had issues too, but this error in 1.18.0 is different).  Thanks!

[11-12-2017 19:20] System.InvalidCastException: Unable to cast object of type 'POEApi.Model.Gear' to type 'POEApi.Model.Gem'.
   at POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 19:20] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 19:20] Error reading character data for character 'AntiquatedRelic', Exception info: 
[11-12-2017 19:20] System.Exception: Error reading character data for AntiquatedRelic, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by TardisMaximus** [comment]
In addition to the above, this was using a fresh load of Procurement with full administrative privileges.  Let me know if you need any other info.

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.

**Comment by TardisMaximus** [comment]
Awesome, giving that a try now.

**Comment by TardisMaximus** [comment]
Worked like a charm!

**Comment by Stickymaddness** [comment]
If someone can send me a .bin file containing a stygian vise belt with a jewel in it, I'll look into a fix

**Comment by TardisMaximus** [comment]
Here you go!
[AntiquatedRelic.zip](https://github.com/Stickymaddness/Procurement/files/1556935/AntiquatedRelic.zip)

**Comment by Stickymaddness** [comment]
Thanks @TardisMaximus !
 
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.

**Comment by TardisMaximus** [comment]
Awesome, thank you for all of your work.  Love the utility!
