### ISSUE TITLE
Trade tab crash

### ISSUE THREAD

**Issue by BigBangBong** [Stickymaddness/Procurement#826]
I'm using Procurement for 1 month right now, and everything was good but today when i make a new buyout prices and click on trade tab it make it crashed every time so i can't make any sell offers now :(

There is my debuginfo.

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1907809/DebugInfo.log)

**Comment by aydjay** [comment]
Remove the nets from your tab - they are currently lacking support

**Comment by thailyn** [comment]
I don't think this is relating to the nets.  While nets aren't supported [yet], they are coming up as "Unknown" currency items.  I also see in my debug log stuff like "`ProxyMapper.GetOrbType Failed! ItemType = Strong Steel Net`" and there aren't any problems.  I can't recreate this issue when I have nets and/or bestiary orbs (with and without captured beasts of each rarity) in the Trading tab.  But I don't use the trading stuff in Procurement so I could be missing something.

I'm more interested in the "Captured Soul of Shock and Horror" item.  Pantheon souls are also not supported [yet], and from the formatting and style of the item box on the [wiki page](https://pathofexile.gamepedia.com/Captured_Soul_of_Shock_and_Horror) I would not be surprised if Pantheon souls have a name but no type line, and the `TypeLine` is the only reasonable value that could possibly be null to cause the `NullReferenceException` in `Procurement.ViewModel.Filters.ForumExport.EssenceFilter.Applicable(Item item)`.  Nets and bestiary orbs appear to always have a non-null type line right now.  I've never gotten a Pantheon soul in game where I could test this.

The debug log says:

    [13-04-2018 16:42] System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
       w POEApi.Model.ProxyMapper.GetStackInfo(List`1 list)
       w POEApi.Model.Currency..ctor(Item item)
       w POEApi.Model.ItemFactory.GetCurrency(Item item)
       w POEApi.Model.ItemFactory.Get(Item item)
    [13-04-2018 16:42] ItemFactory unable to instantiate type : Captured Soul of Shock and Horror

@BigBangBong , would you be able to attach the `.bin` files for the account encountering this issue, or at least the one containing the Pantheon soul?

**Comment by aydjay** [comment]
That looks like it's much more likely to be the issue rather than the nets. +1

**Comment by thailyn** [comment]
And now I finally got a captured soul and can confirm there is a problem.  Technically, a captured soul is a currency item.  However, it is not stackable, and in the JSON the item's Properties is null, so attempting to get the stack size from the properties throws an exception.  I'll send a PR to fix this shortly.

Side note: apparently captured souls can not be put into your stash, so they only exist in your inventory.

Contents from the character's bin file for the captured soul:
`{"verified":false,"w":1,"h":2,"ilvl":0,"icon":"https:\/\/web.poecdn.com\/image\/Art\/2DItems\/Maps\/SinFlaskFull.png?scale=1&scaleIndex=0&w=1&h=2&v=5b5013c16e62ef679c9b044358ff87cf","league":"SSF Bestiary","id":"324fd79cea5be0b3d3a521251edd6417fb470bb8262d4af865298d84a6429674","name":"","typeLine":"Captured Soul of The Forgotten Soldier","identified":true,"lockedToCharacter":true,"descrText":"A captured Soul. Give to Sin to unlock a secondary Pantheon Power.","flavourText":["Though his mind decayed with each passing wave,\r","the Brine King stood steadfast in his hatred,\r","and wore it like a shell, protecting himself \r","from his failure to sire a worthy heir."],"frameType":5,"category":{"currency":["soul"]},"x":0,"y":3,"inventoryId":"MainInventory"}`

Procurement is able to fetch inventory and stash tabs without crashing (but has errors it logs to the debug log), but 1) the captured soul simply does not show up in my character's inventory in Procurement, since there are exceptions when the ItemFactory tries to create an item so an UnknownItem placeholder is used, which does not show up in the UI; and 2) the app crashes if I refresh any tabs.

      [20-05-2018 1:43] Error in EquipedItems.setProperty : System.ArgumentNullException: Value cannot be null.
    Parameter name: key
       at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
       at POEApi.Model.EquipedItems.setProperty(Item item) in C:\Users\[...]\Procurement\POEApi.Model\EquipedItems.cs:line 53
    [20-05-2018 1:43] Target property : 
    [20-05-2018 1:43] System.NullReferenceException: Object reference not set to an instance of an object.
       at POEApi.Model.ProxyMapper.GetStackInfo(List`1 list) in C:\Users\[...]\Procurement\POEApi.Model\ProxyMapper.cs:line 311
       at POEApi.Model.StackableItem..ctor(Item item) in C:\Users\[...]\Procurement\POEApi.Model\StackableItem.cs:line 9
       at POEApi.Model.Currency..ctor(Item item) in C:\Users\[...]\Procurement\POEApi.Model\Currency.cs:line 8
       at POEApi.Model.ItemFactory.GetCurrency(Item item) in C:\Users\[...]\Procurement\POEApi.Model\ItemFactory.cs:line 81
       at POEApi.Model.ItemFactory.Get(Item item) in C:\Users\[...]\Procurement\POEApi.Model\ItemFactory.cs:line 36
    [20-05-2018 1:43] ItemFactory unable to instantiate type : Captured Soul of The Forgotten Soldier

Error that causes the crash:

    [20-05-2018 1:45] Application Version: Procurement 1.21.0
    [20-05-2018 1:45] 
    CurrentCulture: en-US
    CurrentUICulture: en-US
    Operating System: Microsoft Windows NT 6.2.9200.0
    Current League: SSF Bestiary

    [20-05-2018 1:45] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Procurement.ViewModel.Filters.ForumExport.EssenceFilter.Applicable(Item item) in C:\Users\[...]\Procurement\Procurement\ViewModel\Filters\ForumExport\EssenceFilter.cs:line 41
       at Procurement.ViewModel.ForumExportVisitors.VisitorBase.<>c__DisplayClass8_0.<runFilter>b__0(Item i) in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportVisitors\VisitorBase.cs:line 37
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at Procurement.ViewModel.ForumExportVisitors.VisitorBase.runFilter(IFilter filter, IEnumerable`1 items) in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportVisitors\VisitorBase.cs:line 37
       at Procurement.ViewModel.ForumExportVisitors.VisitorBase.runFilter[T](IEnumerable`1 items) in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportVisitors\VisitorBase.cs:line 31
       at Procurement.ViewModel.ForumExportVisitors.EssenceVisitor.Visit(IEnumerable`1 items, String current) in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportVisitors\EssenceVisitor.cs:line 16
       at Procurement.ViewModel.ForumExportViewModel.getFinal(IEnumerable`1 items) in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportViewModel.cs:line 260
       at Procurement.ViewModel.ForumExportViewModel.updateText() in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportViewModel.cs:line 247
       at Procurement.ViewModel.ForumExportViewModel.setSelectedTabs() in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportViewModel.cs:line 131
       at Procurement.ViewModel.ForumExportViewModel..ctor() in C:\Users\[...]\Procurement\Procurement\ViewModel\ForumExportViewModel.cs:line 107
       at Procurement.Controls.ForumExport..ctor() in C:\Users\[...]\Procurement\Procurement\Controls\ForumExport.xaml.cs:line 14
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(Type type, Boolean nonPublic)
       at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
       at System.Activator.CreateInstance(Type type, Object[] args)
       at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
       at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
       at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
       at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateInstance(XamlType xamlType, Object[] args)
       at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
       at System.Xaml.XamlObjectWriter.WriteEndObject()
       at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
       at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
       at Procurement.View.TradingView.InitializeComponent() in C:\Users\[...]\Procurement\Procurement\View\TradingView.xaml:line 1
       at Procurement.View.TradingView..ctor() in C:\Users\[...]\Procurement\Procurement\View\TradingView.xaml.cs:line 10
       at Procurement.ViewModel.ScreenController.execute(Object obj) in C:\Users\[...]\Procurement\Procurement\ViewModel\ScreenController.cs:line 66
       at Procurement.ViewModel.DelegateCommand.Execute(Object parameter) in C:\Users\[...]\Procurement\Procurement\ViewModel\DelegateCommand.cs:line 22
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
