### ISSUE TITLE
I can't log in because of - [Error] Downloading stash for Bestiary

### ISSUE THREAD

**Issue by Beastmodee** [Stickymaddness/Procurement#842]
debug info

[24-05-2018 0:15] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at POEApi.Model.Gear..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[24-05-2018 0:15] ItemFactory unable to instanciate type : Sulphur Flask
[24-05-2018 0:15] Error downloading stash for Bestiary, exception details: System.Exception: ItemFactory unable to instanciate type : Sulphur Flask
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[24-05-2018 0:15] System.Exception: Downloading stash for Bestiary, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by thailyn** [comment]
Hi.  Please update to the latest version of Procurement (currently 1.21.0) and try to log in again.  If you continue to have issues, attach the latest version of the DebugInfo.log file again.  Thanks!
