### ISSUE TITLE
Can't log into Procurement since I had to agree to POE's new User Agreement (May 22?)

### ISSUE THREAD

**Issue by mysticmica** [Stickymaddness/Procurement#846]
Tried using Procurement after agreeing to the new POE User Agreement. Got an error stating that I was using the wrong username or password.

- Retyped both elements in the Procurement login screen, still received the same error.
- Waited 24 hours in case of hardware/server issues, still got the same error.
- Uninstalled Procurement and reinstalled with Procurement 1.21, still same error.
- Changed POE password, logged out of POE and Procurement, retried with new password and still got the same error.

The DebugInfo file after the password change/retry reads:
[25-05-2018 20:43] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User mysticmica@gmx.com
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by thailyn** [comment]
Thanks for the report.  The error message is misleading, as the password probably isn't incorrect (particularly after your investigation).  I was having the same problems yesterday, and I have a PR (#844) that fixed the issue for me.  It looks like the login process changed a bit when they rolled out the new ToS. (Feel free to edit your email address out of the DebugInfo.log excerpt.)

**Comment by mysticmica** [comment]
Thanks for the Fast responses! Seems to be working now.
