### ISSUE TITLE
Can't log in because:  [Error] Downloading stash for SSF Standard

### ISSUE THREAD

**Issue by bstanley78** [Stickymaddness/Procurement#864]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2059240/DebugInfo.log)

DebugInfo attached!

**Comment by thailyn** [comment]
Hi, thanks for the report.  The log is indicating Procurement is getting a 404 error (resource not found) when it attempts to use the API.  This is most likely a transient issue on GGG's side.

Please try again in a short while and let us know if the issue continues.  Thanks!

    [31-05-2018 11:57] Error downloading stash for SSF Standard, exception details: System.Net.WebException: The remote server returned an error: (404) Not Found.
       at System.Net.HttpWebRequest.GetResponse()
       at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
       at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
       at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
       at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
       at POEApi.Model.POEModel.GetStash(String league, String accountName)
    [31-05-2018 11:57] System.Exception: Downloading stash for SSF Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
       at POEApi.Model.POEModel.GetStash(String league, String accountName)
       at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
       at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
       at System.Threading.Tasks.Task.Execute()
