### ISSUE TITLE
Procurement Bug

### ISSUE THREAD

**Issue by Necrodude** [Stickymaddness/Procurement#880]
The error suggested I post my log here. 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2226430/DebugInfo.log)

**Comment by thailyn** [comment]
This issue was caused by Procurement sending too many requests to GGG's API (how it gets information about what items you have).  It should be a temporary issue.  Please let us know if the issue continues.  Normally Procurement makes sure it does not go over the limit.  Were you perhaps reopening Procurement multiple times in a short period of time (e.g., minutes)?

The relevant error message from `DebugInfo.log`:

```
[24-07-2018 21:01] Error downloading stash for Standard, exception details: System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[24-07-2018 21:01] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__30.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass29_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
```
