### ISSUE TITLE
[1.24.0] [Error] The remote server returned an error: (503) Server Unavailable.

### ISSUE THREAD

**Issue by Xetaxheb** [Stickymaddness/Procurement#898]
Pathofexile.com isn't down or broken or anything, but this instantly returns when I try to login with poesessid.

```
[10-12-2018 21:53] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[10-12-2018 21:53] System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass29_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by Xetaxheb** [comment]
Login is behind cloudflare.
