### ISSUE TITLE
Downloading Bloodlines/Torment for first time and this happened

### ISSUE THREAD

**Issue by PaulNations** [Stickymaddness/Procurement#91]
I have not been playing in Torment/Bloodlines much and didn't really want Procurement to mess with it because I have quite a few stash tabs. But tonight I decided to try to sell some of the stuff I had in the T/B league and enabled it and got the error below the line..

I went into settings.xml and commented out the T/B line and it ran fine. I uncommented the T/B and commented the Standard league and it ran fine. It's only when I have both leagues selected that I get the error below.

Thank you for a most excellent program.
____________________________________________________________________________
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[12-01-2015 17:01] Error starting PoeTradeOnlineHelper: System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Procurement.Utility.PoeTradeOnlineHelper.Start()
[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 1
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 66
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 67
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 68
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 69
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 70
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 71
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[07-02-2015 19:33] 
Exception attempting to get items by tab for tabId : 72
Current TabIds:
Stash2
Stash3
Stash4
Stash5
Stash6
Stash7
Stash8
Stash9
Stash10
Stash11
Stash12
Stash13
Stash14
Stash15
Stash16
Stash17
Stash18
Stash19
Stash20
Stash21
Stash22
Stash23
Stash24
Stash25
Stash26
Stash27
Stash28
Stash29
Stash30
Stash31
Stash32
Stash33
Stash34
Stash35
Stash36
Stash37
Stash38
Stash39
Stash40
Stash41
Stash42
Stash43
Stash44
Stash45
Stash46
Stash47
Stash48
Stash49
Stash50
Stash51
Stash52
Stash53
Stash54
Stash55
Stash56
Stash57
Stash58
Stash59
Stash60
Stash61
Stash62
Stash63
Stash64
Stash65
End of TabIds.
Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at POEApi.Model.Stash.GetItemsByTab(Int32 tabId)

[09-04-2015 22:18] Error downloading stash for Torment/Bloodlines, exception details: System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league)
[09-04-2015 22:18] System.Exception: Downloading stash for Torment/Bloodlines, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Sorry I have taken so long to reply to your issue, is it still a problem? Looking at the log there seems to be a number of connection related issues, specifically 503 Server Unavailable, which is a server side issue on GGG's side. 

I know that they were having some issues, but it should all be sorted out now.

**Comment by PaulNations** [comment]
Sorry. I quit playing. My account was hacked and GGG refused to do anything more than suggest I change my password. I’ve spent too much money with them for such crappy service.

Paul Nations
(501) 371-2042

**Comment by Stickymaddness** [comment]
Sorry to hear about your account, thanks for replying to the ticket anyway.
