### ISSUE TITLE
Unable to login, release 1.24.2

### ISSUE THREAD

**Issue by plugsz** [Stickymaddness/Procurement#924]
Unable to login with the new release, using sessionID to login since I play POE via Steam
As seen via the Procurement Gui
_**Procurement 1.24.2 Initialized.
Authenticating ....                                                                    
[Error] Cloud flare clearance failed, please wait one minute and try again
Authenticating ....                                                                    [OK]
Fetching account name...                                                                  
[Error] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log**_

`[23-12-2018 17:22] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[23-12-2018 17:22] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: One or more errors occurred. ---> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 3 attempt(s).
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- End of inner exception stack trace ---
   at POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass25_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[23-12-2018 17:23] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[23-12-2018 17:23] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[23-12-2018 17:23] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[23-12-2018 17:23] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass25_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()`

**Comment by plugsz** [comment]
This definitely looks like your culprit, as I can use the same URL and get the page to open myself
_[23-12-2018 17:34] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name', allowAutoRedirects=, requestData='': **The remote server returned an error: (401) Unauthorized.**
[23-12-2018 17:34] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: **(401) Unauthorized._**

**Comment by Shixor** [comment]
I have the same error and I'm not using Steam

**Comment by nkstnkst** [comment]
Having the same problem.

**Comment by Stickymaddness** [comment]
This has been fixed in the newer releases of Procurement, if you still encounter issues please open a new ticket.
