### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by chococum** [Stickymaddness/Procurement#926]
[Error] The remote server returned an error: (503) Server Unavailable.

**Comment by thailyn** [comment]
Please make sure you are using the [latest version of Procurement](https://github.com/Stickymaddness/Procurement/releases/latest) and are logging in using Session ID.  GGG changed how the login process works with the Betrayal league, and only Session ID is supported with Procurement right now.

**Comment by nkstnkst** [comment]
I am using the latest release, but still got the error.

**Comment by Stickymaddness** [comment]
Are you still experiencing this error?

**Comment by EVPerry** [comment]
cant find sess id

**Comment by thailyn** [comment]
Do you mean you don't know how to get your Session ID?  Please see [this page](https://code.google.com/archive/p/procurement/wikis/LoginWithSessionID.wiki) for some (slightly outdated) information on getting the information; it's stored in the POESESSID cookie.  If you're still having trouble, please tell us what browser you're using to log in to the pathofexile.com website.

**Comment by EVPerry** [comment]
id didnt work. chrome

**Comment by thailyn** [comment]
Logging in with the Session ID didn't work?  You could attach your `DebugInfo.log` file and I can see if there's anything particular in there, but I think the login process is just a little fickle since CloudFlare protection was added and I haven't figured out how/why.  I would suggest logging out and back in in your browser, which should get you a new Session ID value, and try that in Procurement.  From anecdotal experience, it might also help to wait a little bit before trying again.

**Comment by EVPerry** [comment]
HOW DO u find debug? i think cloud is fucking me

**Comment by thailyn** [comment]
It would be a file named `DebugInfo.log` that is in the same directory as `Procurement.exe`.

**Comment by EVPerry** [comment]
[24-02-2019 14:17] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: One or more errors occurred. ---> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 3 attempt(s).
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- End of inner exception stack trace ---
   at POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[24-02-2019 14:38] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.

**Comment by EVPerry** [comment]
wtf

**Comment by EVPerry** [comment]
it worked now

**Comment by chococum** [comment]
I havent played PoE for a while but last time I tried it worked, although it's slow to start

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
