### ISSUE TITLE
Error loading character data 1.9.2

### ISSUE THREAD

**Issue by budha2000** [Stickymaddness/Procurement#97]
[26-04-2015 11:49] Error reading character data for character 'DarkAzazell', Exception info: 
[26-04-2015 11:49] System.Exception: Error reading character data for DarkAzazell, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by budha2000** [comment]
I got the problem ... the account name had wrong spelling.
