### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by SarkyMarki** [Stickymaddness/Procurement#98]
Been having a few errors lately. This is the first time I have received the message to open a ticket.
Below is the text from the DebugInfo.log for today:

[27-04-2015 11:11] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   at ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
[27-04-2015 11:11] JSON Serialization Failed: base64 bytes:
[27-04-2015 11:11] ZmFsc2U=
[27-04-2015 11:11] END
[27-04-2015 11:11] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-04-2015 11:11] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The error is due to getting empty data back from GGG, is this still an issue?

**Comment by SarkyMarki** [comment]
Hi,

yes this is still an issue...

I sometimes get this message too...

“[Error] Error reading character data for M_A_N_VI, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.”

I would be incredibly grateful if you could help

Thanks
Mark

**Comment by Stickymaddness** [comment]
For the character data error, make sure that you're running the latest version of Procurement (1.9.2) and entering your account name (case sensitive)

**Comment by Stickymaddness** [comment]
To clarify the account name field:

![accountname](https://cloud.githubusercontent.com/assets/6553902/7933116/4fd693e8-091d-11e5-80f5-eda0bde0a530.PNG)

**Comment by SarkyMarki** [comment]
Hi,

Thanks for the email

I think I am using the software correctly.



It loads fine for a while then gives the error message

Mark

**Comment by Stickymaddness** [comment]
Ok, which error are you getting currently? The first one you logged or the second one relating to your account name?

If you're getting the first error, make sure you're running the latest version of .NET

**Comment by SarkyMarki** [comment]
To get you that screen shot I installed procurement on a different machine than I normally use.
The error I get at the moment is the one I sent you.

I tend to get both errors on my regular gaming PC at home.

Thanks
Mark

**Comment by SarkyMarki** [comment]
Hi,

I checked from my games machine at home and got the same error message:



cheers
Mark

**Comment by LEOPARD1985** [comment]
[Ошибка] Downloading stash for Стандарт, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues что делать

**Comment by Stickymaddness** [comment]
Which error are you getting? You have listed two errors.

Please test with 1.9.3 and paste me the exact error you are getting.

**Comment by SarkyMarki** [comment]
Hi,

Thanks for the email, this is the error I receive:

Loading Standard Stash Tab 270...                                                         [OK]
Loading Standard Stash Tab 271...                                                         [OK]
Loading Standard Stash Tab 272...                                                         [OK]
Loading Standard Stash Tab 273...                                                         [OK]
Loading Standard Stash Tab 274...                                                         [OK]
Loading Standard Stash Tab 275...                                                         [OK]
Loading Standard Stash Tab 276...                                                         [OK]
Loading Standard Stash Tab 277...                                                         [OK]
Loading Standard Stash Tab 278...                                                         [OK]
Loading Standard Stash Tab 279...                                                         [OK]
Loading Standard Stash Tab 280...                                                         [OK]
Loading Standard Stash Tab 281...                                                         [OK]
Loading Standard Stash Tab 282...                                                         [OK]
Loading Standard Stash Tab 283...                                                         [OK]
Loading M_A_N_VI's inventory...                                                           

[Error] Error reading character data for M_A_N_VI, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

I am not in offline mode

Thanks
Mark

**Comment by Stickymaddness** [comment]
Ok,

Open up your settings file and set Procurement to download no characters:

<Setting name="DownloadOnlyMyCharacters" value="True" />

and see if you are able to login

**Comment by SarkyMarki** [comment]
Hi,

So I set 

<Setting name="DownloadOnlyMyLeagues" value="false" />

and left 

<List name="MyCharacters" />

blank and it logs in fine 

Mark
